async function renderList(){
  if(!currentUser){nav('auth');toast('Sign in to list a vacancy');return}
  layout(`<section><div class="section-head"><div><h1>List a vacancy</h1><p class="muted">Create a property once, then add bedsitters, studios, bedrooms or apartments under it.</p></div></div><div id="listingHost" class="empty">Loading your properties…</div><div class="section-head"><h2>Your vacancies</h2></div><div id="mine"><div class="empty">Loading your vacancies…</div></div></section>`);
  const host=document.querySelector('#listingHost'); const properties=(await VACANCY_BACKEND.myProperties()).filter(p=>!p.marketCode||p.marketCode===marketCode);
  const labels=market().locationLabels; const unitTypes=marketUI().unitTypes;
  const commonUnitFields=`<label>Unit type<select name="unitType">${unitTypes.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Listing name<input name="roomName" required placeholder="Modern bedsitter near KU"></label><label>Rent amount<input name="rentAmount" type="number" min="1" required></label><label>Currency<select name="rentCurrency">${Object.values(MARKETS).map(m=>`<option value="${m.currency}" ${m.currency===market().currency?'selected':''}>${m.flag} ${m.currency}</option>`).join('')}</select></label><label>Rent period<select name="rentPeriod"><option value="month" ${market().rentPeriod==='month'?'selected':''}>Per month</option><option value="week" ${market().rentPeriod==='week'?'selected':''}>Per week</option><option value="night">Per night</option></select></label><label>Deposit / bond<input name="deposit" type="number" min="0"></label><label>Available from<input name="availableFrom" type="date" required></label><label>Minimum stay (weeks)<input name="minimumStayWeeks" type="number" min="1" value="8"></label><label>Max occupants<select name="maxOccupants"><option value="1">1 occupant</option><option value="2">2 occupants</option><option value="3">3 occupants</option><option value="4">4 occupants</option></select></label><label>Furnished<select name="furnished"><option value="false">No</option><option value="true">Yes</option></select></label><label>Ensuite<select name="ensuite"><option value="true">Yes</option><option value="false">No</option></select></label><label>Utilities included<select name="billsIncluded"><option value="false">No / varies</option><option value="true">Yes</option></select></label><label class="wide">About this unit<textarea name="description" required maxlength="1200"></textarea></label><label class="wide">Photos<input name="images" type="file" accept="image/jpeg,image/png,image/webp" multiple><span class="muted">Up to 8 images, 10MB each.</span></label>`;
  function normalise(f){return {...f,marketCode, country:market().label,furnished:f.furnished==='true',ensuite:f.ensuite==='true',billsIncluded:f.billsIncluded==='true',petsConsidered:f.petsConsidered==='true',smokingAllowed:f.smokingAllowed==='true',waterAvailable:f.waterAvailable==='true',electricityAvailable:f.electricityAvailable==='true',securityAvailable:f.securityAvailable==='true',internetAvailable:f.internetAvailable==='true'}}
  function bindPublish(form, existingPropertyId=null){form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form),files=[...form.elements.images.files],f=Object.fromEntries(fd);delete f.images;const input=normalise(f);try{const result=existingPropertyId?await VACANCY_BACKEND.createRoomVacancyForProperty(existingPropertyId,input):await VACANCY_BACKEND.createListing(input);const vacancyId=Array.isArray(result)?result[0]:result;if(!existingPropertyId){if(!input.publicLatitude||!input.publicLongitude)throw new Error('Choose an approximate public map location');await VACANCY_BACKEND.setVacancyPublicLocation(vacancyId,input.publicLatitude,input.publicLongitude)}VACANCY_BACKEND.trackEvent('listing_published',vacancyId,'#list');let warning='';if(files.length){try{await VACANCY_BACKEND.uploadListingImages(vacancyId,files)}catch(imgErr){warning=' Images need retry: '+imgErr.message}}toast('Vacancy published.'+warning);await refreshVacancies();await renderList()}catch(err){toast(err.message)}}}
  function showNew(){host.className='';host.innerHTML=`<div class="panel"><div class="row space"><div><strong>New property</strong><div class="muted">Property details are reused by every unit you add later.</div></div>${properties.length?'<button class="ghost" id="useExisting">Use existing property</button>':''}</div><form id="listingForm" class="form-grid"><h2 class="wide">Location</h2><label>${labels.region}<input name="region" required></label><label>${labels.city}<input name="city" required></label><label>${labels.locality}<input name="locality" required></label><label>Nearby landmark<input name="landmark" placeholder="Station, campus, main road…"></label><label>${labels.postal} (optional)<input name="postal" inputmode="text"></label><label class="wide">Exact address / directions<input name="address" required><span class="muted">Kept private from public search.</span></label><div class="wide"><strong>Approximate public map location</strong><div id="newPropertyMap" class="listing-map"></div><div class="map-help">Tap the map to place the public pin. Keep it approximate if you do not want to reveal the exact entrance.</div><input type="hidden" name="publicLatitude"><input type="hidden" name="publicLongitude"></div><h2 class="wide">Property</h2><label>Property type<select name="propertyType"><option>Apartment block</option><option>Apartment</option><option>House</option><option>Maisonette</option><option>Hostel</option><option>Compound</option></select></label><label>Parking spaces<input name="parkingSpaces" type="number" min="0" max="50" value="0"></label><label>Water available<select name="waterAvailable"><option value="true">Yes</option><option value="false">No / unreliable</option></select></label><label>Electricity available<select name="electricityAvailable"><option value="true">Yes</option><option value="false">No</option></select></label><label>Security<select name="securityAvailable"><option value="true">Yes</option><option value="false">No</option></select></label><label>Internet / fibre<select name="internetAvailable"><option value="false">No / unknown</option><option value="true">Available</option></select></label><label>Smoking on property<select name="smokingAllowed"><option value="false">No smoking</option><option value="true">Smoking allowed</option></select></label><label>Pets considered<select name="petsConsidered"><option value="false">No / ask first</option><option value="true">Yes</option></select></label><label class="wide">About the property<textarea name="household" required maxlength="1200"></textarea></label><h2 class="wide">Unit & availability</h2>${commonUnitFields}<button class="primary wide">Publish vacancy</button></form></div>`;if(properties.length)document.querySelector('#useExisting').onclick=showExisting;bindPublish(document.querySelector('#listingForm'));initListingMapPicker('newPropertyMap','publicLatitude','publicLongitude')}
  function showExisting(){host.className='';host.innerHTML=`<div class="panel"><div class="row space"><div><strong>Add a unit to an existing property</strong><div class="muted">Location and property facilities are reused automatically.</div></div><button class="ghost" id="createProperty">Create new property</button></div><form id="existingListingForm" class="form-grid"><label class="wide">Property<select id="propertyChoice">${properties.map(p=>`<option value="${p.id}">${escapeHtml(p.title)} — ${escapeHtml(p.locality)}, ${escapeHtml(p.city)}</option>`).join('')}</select></label><div id="inheritSummary" class="notice wide"></div><label>Smoking<select name="smokingOverride"><option value="">Same as property</option><option value="false">Override: no smoking</option><option value="true">Override: smoking allowed</option></select></label><label>Pets<select name="petsOverride"><option value="">Same as property</option><option value="false">Override: not considered</option><option value="true">Override: considered</option></select></label>${commonUnitFields}<button class="primary wide">Publish vacancy</button></form></div>`;document.querySelector('#createProperty').onclick=showNew;const choice=document.querySelector('#propertyChoice'),summary=document.querySelector('#inheritSummary'),form=document.querySelector('#existingListingForm');const refresh=()=>{const p=properties.find(x=>x.id===choice.value);summary.textContent=`${p.locality}, ${p.city} · ${p.waterAvailable?'water':'water not confirmed'} · ${p.electricityAvailable?'electricity':'no electricity'} · ${p.securityAvailable?'security':'security not confirmed'} · ${p.parkingSpaces} parking`};const bind=()=>bindPublish(form,choice.value);choice.onchange=()=>{refresh();bind()};refresh();bind()}
  if(properties.length)showExisting();else showNew(); await loadMine();
}
async function loadMine(){
  const host=document.querySelector('#mine'); if(!host)return;
  try{
    const rows=await VACANCY_BACKEND.myVacancies();
    if(!rows.length){host.innerHTML='<div class="empty">You have no vacancies yet.</div>';return}
    const groups=new Map();
    for(const row of rows){const property=row.rooms.properties;const key=property.id;if(!groups.has(key))groups.set(key,{property,rows:[]});groups.get(key).rows.push(row)}
    host.innerHTML=[...groups.values()].map(group=>`<details class="panel property-tree" open><summary><div><strong>${escapeHtml(group.property.title||group.property.suburb+' property')}</strong><div class="muted">${escapeHtml(group.property.suburb)}, ${escapeHtml(group.property.city)} · ${group.rows.length} unit${group.rows.length===1?'':'s'}</div></div><span>⌄</span></summary><div class="property-tree-body tree-indent stack">${group.rows.map(row=>`<div class="row space room-manage"><div><strong>${escapeHtml(row.rooms.name)}</strong><div class="muted">${(Object.values(MARKETS).find(m=>m.currency===row.rent_currency)||marketForCountry(group.property.country)).currencyLabel} ${Number(row.rent_amount??row.monthly_rent).toLocaleString((Object.values(MARKETS).find(m=>m.currency===row.rent_currency)||marketForCountry(group.property.country)).locale)}/${row.rent_period||marketForCountry(group.property.country).rentPeriod} · ${row.status}</div></div><div class="row"><button class="ghost" data-edit="${row.id}">Edit</button>${row.status==='active'?`<button class="ghost" data-status="paused" data-id="${row.id}">Pause</button>`:''}${row.status==='paused'?`<button class="ghost" data-status="active" data-id="${row.id}">Reactivate</button>`:''}<button class="ghost" data-reconfirm="${row.id}">Still available</button>${row.status!=='filled'?`<button class="danger" data-status="filled" data-id="${row.id}">Mark filled</button>`:''}</div></div>`).join('')}</div></details>`).join('');
    document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>nav('edit',b.dataset.edit));
    document.querySelectorAll('[data-reconfirm]').forEach(b=>b.onclick=async()=>{try{await VACANCY_BACKEND.reconfirmVacancy(b.dataset.reconfirm);toast('Availability reconfirmed');await refreshVacancies();await loadMine()}catch(err){toast(err.message)}});
    document.querySelectorAll('[data-status]').forEach(b=>b.onclick=async()=>{try{await VACANCY_BACKEND.setVacancyStatus(b.dataset.id,b.dataset.status);toast(`Vacancy ${b.dataset.status}`);await refreshVacancies();await loadMine()}catch(err){toast(err.message)}})
  }catch(err){host.innerHTML=`<div class="empty">${escapeHtml(err.message)}</div>`}
}
