const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {Webhook}=require('standardwebhooks');
const secret=crypto.randomBytes(32).toString('base64'),wh=new Webhook(secret);
const base={user:{email:'owner@example.invalid',new_email:'new@example.invalid',user_metadata:{display_name:'<img src=x onerror=alert(1)>'}},email_data:{email_action_type:'signup',token_hash:'fresh-hash',redirect_to:'https://getvacancy.site/'}};
const mod=()=>import('../supabase/functions/send-auth-email/handler.mjs');
function signed(payload,age=0){const body=JSON.stringify(payload),date=new Date(Date.now()+age),id='test-event';return new Request('https://test.invalid',{method:'POST',body,headers:{'webhook-id':id,'webhook-timestamp':String(Math.floor(date/1000)),'webhook-signature':wh.sign(id,date,body)}})}
test('signup and recovery select published templates and fresh per-message URLs',async()=>{const {buildMessages}=await mod();for(const type of ['signup','recovery']){const msg=buildMessages({...base,email_data:{...base.email_data,email_action_type:type}},'https://project.supabase.co')[0];assert.equal(msg.template.id,type==='signup'?'vacancy-confirm-email':'vacancy-reset-password');assert.equal(new URL(msg.template.variables.ACTION_URL).searchParams.get('type'),type);assert.equal(new URL(msg.template.variables.ACTION_URL).searchParams.get('token'),'fresh-hash');assert.match(msg.template.variables.DISPLAY_NAME,/&lt;img/);assert.equal(msg.html,undefined);assert.equal(msg.subject,undefined)}});
test('email change maps old and new recipients to correct hashes',async()=>{const {buildMessages}=await mod();let p={...base,email_data:{...base.email_data,email_action_type:'email_change',token_hash:'new-address-hash',token_hash_new:'old-address-hash'}};const messages=buildMessages(p,'https://project.supabase.co');assert.equal(messages.length,2);assert.deepEqual(messages[0].to,[base.user.email]);assert.match(messages[0].text,/old-address-hash/);assert.deepEqual(messages[1].to,[base.user.new_email]);assert.match(messages[1].text,/new-address-hash/);delete p.email_data.token_hash_new;assert.equal(buildMessages(p,'https://project.supabase.co').length,1)});
test('signed request accepted, invalid or expired signatures cannot send',async()=>{const {createHandler}=await mod();let sent=[];const h=createHandler({verify:(s,hs)=>wh.verify(s,hs),apiKey:'synthetic',supabaseUrl:'https://project.supabase.co',send:async(url,o)=>{sent.push(o);return new Response('{}')}});assert.equal((await h(signed(base))).status,200);assert.equal(sent.length,1);assert.equal(sent[0].headers['Idempotency-Key'],'vacancy-auth/test-event/0');assert.equal((await h(new Request('https://test.invalid',{method:'POST',body:JSON.stringify(base)}))).status,401);assert.equal((await h(signed(base,-600000))).status,401);assert.equal(sent.length,1)});
test('missing tokens and unknown actions fail without sending',async()=>{const {createHandler}=await mod();let calls=0;for(const d of [{email_action_type:'signup'},{email_action_type:'unexpected'}]){const h=createHandler({verify:()=>({...base,email_data:d}),apiKey:'x',supabaseUrl:'https://project.supabase.co',send:async()=>{calls++;return new Response('{}')}});assert.equal((await h(signed(base))).status,400)}assert.equal(calls,0)});
test('provider failures are not reported as successful delivery',async()=>{const {createHandler}=await mod();for(const status of [422,429,500]){const h=createHandler({verify:()=>base,apiKey:'x',supabaseUrl:'https://project.supabase.co',send:async()=>new Response('{}',{status})});assert.equal((await h(signed(base))).status,502)}});
test('remaining supported auth events produce bounded messages',async()=>{const {buildMessages}=await mod();for(const type of ['invite','magiclink','reauthentication','password_changed_notification','email_changed_notification','phone_changed_notification','identity_linked_notification','identity_unlinked_notification','mfa_factor_enrolled_notification','mfa_factor_unenrolled_notification']){assert.equal(buildMessages({...base,email_data:{...base.email_data,email_action_type:type,token:'12345678'}},'https://project.supabase.co').length,1)}});

test('anonymous guest can confirm first email without an old mailbox',async()=>{const {buildMessages}=await mod();const messages=buildMessages({user:{email:'',new_email:'guest@example.invalid'},email_data:{email_action_type:'email_change',token_hash:'guest-confirmation'}},'https://project.supabase.co');assert.equal(messages.length,1);assert.deepEqual(messages[0].to,['guest@example.invalid']);assert.match(messages[0].text,/guest-confirmation/)});
