const {test,expect}=require('@playwright/test'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const out=path.resolve(__dirname,'../../marketing-checkpoint-artifacts/hosted'),config=JSON.parse(fs.readFileSync(path.join(out,'public-config.json'))),credentials=JSON.parse(fs.readFileSync(path.join(out,'test-credentials.json')));
if(config.url!=='https://raauicmfyjpcuhfzknak.supabase.co')throw Error('Wrong hosted target');
test.use({trace:'off',screenshot:'off'});
function totp(secret){let bits='';for(const c of secret.replace(/=+$/,''))bits+='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(c).toString(2).padStart(5,'0');const key=Buffer.from(bits.match(/.{8}/g).map(b=>parseInt(b,2))),counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const digest=crypto.createHmac('sha1',key).update(counter).digest();return String((digest.readUInt32BE(digest[19]&15)&0x7fffffff)%1000000).padStart(6,'0');}
test('real hosted browser password, MFA and connected report',async({page},info)=>{
 const base='http://127.0.0.1:8765',admin=credentials.users.find(u=>u.admin);let productionAttempts=0,fail=false;
 await page.route('**/*',async route=>{const url=new URL(route.request().url());
  if(url.origin===base){const response=await route.fetch();if(url.pathname==='/'){const headers={...response.headers()};delete headers['content-security-policy'];return route.fulfill({response,headers});}
   if(url.pathname==='/src/backend.js'){const text=(await response.text()).replace('https://xtutkwiivqkgkqjpkxvj.supabase.co',config.url).replace(/const KEY = '[^']+'/,`const KEY = '${config.key}'`);return route.fulfill({response,body:text});}return route.fulfill({response});}
  if(url.origin===config.url&&(url.pathname.startsWith('/auth/v1/')||url.pathname.startsWith('/rest/v1/admin_users')||url.pathname.includes('/rpc/admin_connected_journeys'))){if(fail&&url.pathname.includes('/rpc/admin_connected_journeys'))return route.fulfill({status:503,contentType:'application/json',body:'{"message":"Synthetic interruption"}'});return route.continue();}
  if(url.hostname==='xtutkwiivqkgkqjpkxvj.supabase.co')productionAttempts++;
  return route.fulfill({status:200,contentType:'application/json',body:'[]'});
 });
 await page.goto(base+'/#auth');await page.waitForFunction(()=>booting===false);
 await page.locator('main input[name=email]').fill(admin.email);await page.locator('main input[name=password]').fill(credentials.password);await page.locator('main').getByRole('button',{name:'Sign in',exact:true}).click();
 await page.waitForFunction(()=>!!currentUser&&!currentUser.is_anonymous);
 await page.goto(base+'/#admin');await page.waitForFunction(()=>booting===false);
 await expect(page.locator('#verifyAdminMfa')).toBeVisible();await expect(page.locator('#adminHost')).toHaveCount(0);
 await page.locator('#verifyAdminMfa').click();await expect(page.locator('.mfa-secret')).toBeAttached();const secret=await page.locator('.mfa-secret').textContent();
 // Unrelated operational sections use synthetic responses; authentication and journey RPC are real.
 await page.evaluate(()=>{VACANCY_BACKEND.adminDashboard=async()=>({open_reports:0,oldest_report_hours:0,active_listings:0,users_total:2,properties:0,units:0,enquiries_7d:0,listings_7d:0,errors_24h:0});VACANCY_BACKEND.adminSearch=async()=>({users:[],listings:[]});VACANCY_BACKEND.adminReports=async()=>[];VACANCY_BACKEND.adminAuditLog=async()=>[];VACANCY_BACKEND.adminDailyMetrics=async()=>({total:0,days:7,series:[]});VACANCY_BACKEND.adminOperationalHealth=async()=>({});VACANCY_BACKEND.adminIconRevisions=async()=>[];});
 await page.locator('input[name=code]').fill(totp(secret));await page.locator('[data-mfa-code-form] button').click();await expect(page.locator('.admin-console')).toBeVisible();
 if(await page.locator('.console-menu-toggle').isVisible())await page.locator('.console-menu-toggle').click();await page.locator('[data-section=marketing]').click();
 await expect(page.locator('.console-journey .journey-flow-panel')).toBeVisible();await expect(page.locator('.console-journey .journey-stats')).toContainText('250');
 await page.evaluate(()=>{const notice=document.createElement('p');notice.textContent='DEVELOPMENT — synthetic database records; real hosted Auth and report RPC';notice.style.cssText='background:#fff4cd;padding:12px;position:relative;z-index:10';document.querySelector('.console-journey').prepend(notice);});
 await page.screenshot({path:path.join(out,info.project.name+'-connected-top.png'),fullPage:false});
 await page.locator('.console-journey [data-stage="2"]').click();await expect(page.locator('.console-journey .journey-selection')).toContainText('Review journeys');
 await page.locator('.console-journey .journey-flow-panel').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,info.project.name+'-connected-flow.png'),fullPage:false});
 await page.locator('.console-journey [data-next]').click();await expect(page.locator('.console-journey .journey-selection tbody tr').first()).toContainText('51');
 fail=true;await page.locator('.console-journey .console-refresh').click();await expect(page.locator('.console-journey [role=alert]')).toContainText('Synthetic interruption');await expect(page.locator('.console-journey .journey-stat')).toHaveCount(0);fail=false;
 await page.locator('.console-journey [data-retry]').click();await expect(page.locator('.console-journey .journey-flow-panel')).toBeVisible();
 await page.locator('.console-journey .journey-details').nth(1).locator('summary').focus();await page.keyboard.press('Enter');await expect(page.locator('.console-journey .journey-details').nth(1)).toHaveAttribute('open','');await page.screenshot({path:path.join(out,info.project.name+'-connected-diagnostics.png'),fullPage:false});await page.locator('.console-journey .journey-details').last().locator('summary').focus();await page.keyboard.press('Enter');await page.evaluate(()=>scrollTo(0,document.documentElement.scrollHeight));await page.screenshot({path:path.join(out,info.project.name+'-connected-bottom.png'),fullPage:false});expect(await page.locator('.mobile-nav').isVisible()).toBe(false);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();expect(productionAttempts).toBe(0);
 const cdp=await page.context().newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:200000,uploadThroughput:93750});await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});const metrics=[];for(let i=0;i<3;i++){const start=Date.now(),responsePromise=page.waitForResponse(r=>r.url().includes('/rpc/admin_connected_journeys'));await page.locator('.console-journey .console-refresh').click();const response=await responsePromise;const bytes=(await response.body()).length;await expect(page.locator('.console-journey .journey-flow-panel')).toBeVisible();metrics.push({endToEndMs:Date.now()-start,transferSizes:await response.request().sizes(),uncompressedBytes:bytes,gzipEquivalentBytes:require('node:zlib').gzipSync(await response.body()).length,contentEncoding:response.headers()['content-encoding']||'none'});}fs.writeFileSync(path.join(out,info.project.name+'-connected-performance.json'),JSON.stringify({conditions:{downloadMbps:1.6,uploadMbps:0.75,latencyMs:150,cpuSlowdown:4},events:1000,samples:metrics,note:'Three samples; not production p95. gzipEquivalentBytes is locally computed, not measured wire bytes.'},null,2));await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});await cdp.send('Emulation.setCPUThrottlingRate',{rate:1});
 await page.evaluate(async()=>{for(const f of await VACANCY_BACKEND.mfaFactors())await VACANCY_BACKEND.mfaUnenroll(f.id);await VACANCY_BACKEND.signOut();});
});
