const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const photo='https://lh3.googleusercontent.com/a/example=s96-c',google={id:'user-one',app_metadata:{provider:'google'},email:'alex@gmail.com',user_metadata:{avatar_url:photo}};
function setup(initial,race=false){let profile={id:'user-one',...initial},writes=[],reads=0;const access='header.'+Buffer.from(JSON.stringify({exp:Math.floor(Date.now()/1000)+3600})).toString('base64url')+'.sig';const ctx={window:{URL},URLSearchParams,localStorage:{getItem:()=>JSON.stringify({access_token:access}),removeItem:()=>{}},atob,fetch:async(url,opts)=>{const u=new URL(url);if(opts.method==='PATCH'){const body=JSON.parse(opts.body),field=Object.keys(body)[0];writes.push(body);if(race)profile[field]=field==='display_name'?'Manual name':'user-one/manual.jpg';const expected=u.searchParams.get(field);if(expected==='is.null'?profile[field]==null:profile[field]===expected.slice(3)){Object.assign(profile,body);return {ok:true,text:async()=>JSON.stringify([profile])};}return {ok:true,text:async()=>'[]'};}reads++;return {ok:true,text:async()=>JSON.stringify([profile])}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('app/src/backend.js','utf8'),ctx);return {api:ctx.window.VACANCY_BACKEND,profile:()=>profile,writes,reads:()=>reads};}
test('initial defaults persist and repeat login does not change them',async()=>{const t=setup({display_name:'',avatar_path:null});await t.api.initialiseGoogleProfile(google);assert.equal(t.profile().display_name,'alex');assert.equal(t.profile().avatar_path,photo);await t.api.initialiseGoogleProfile({...google,email:'changed@gmail.com',user_metadata:{avatar_url:'https://lh3.googleusercontent.com/new'}});assert.equal(t.writes.length,2);assert.equal(t.profile().display_name,'alex');assert.equal(t.profile().avatar_path,photo)});
test('custom name and uploaded avatar are preserved',async()=>{const t=setup({display_name:'Chosen',avatar_path:'user-one/manual.jpg'});await t.api.initialiseGoogleProfile(google);assert.equal(t.writes.length,0)});
test('each field defaults independently',async()=>{const t=setup({display_name:'Chosen',avatar_path:null});await t.api.initialiseGoogleProfile(google);assert.equal(t.profile().display_name,'Chosen');assert.equal(t.profile().avatar_path,photo);assert.equal(t.writes.length,1)});
test('concurrent manual edits win',async()=>{const t=setup({display_name:'',avatar_path:null},true);await t.api.initialiseGoogleProfile(google);assert.equal(t.profile().display_name,'Manual name');assert.equal(t.profile().avatar_path,'user-one/manual.jpg')});
test('email and guest accounts do not initialise',async()=>{const t=setup({});await t.api.initialiseGoogleProfile({id:'user-one',email:'a@b.com',app_metadata:{provider:'email'}});await t.api.initialiseGoogleProfile({...google,is_anonymous:true});assert.equal(t.reads(),0)});
test('only Google HTTPS avatar hosts accepted; uploaded storage paths retained',()=>{const {api}=setup({});assert.equal(api.profileAvatarUrl(photo),photo);assert.equal(api.profileAvatarUrl('https://evil.example/photo'),'');assert.equal(api.profileAvatarUrl('http://lh3.googleusercontent.com/photo'),'');assert.match(api.profileAvatarUrl('user-one/avatar.jpg'),/profile-avatars\/user-one\/avatar.jpg$/)});
