// Static preservation checks only. This is not an executed PostgreSQL authorization test.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8').replace(/\r\n/g,'\n');
const original=read('supabase/migrations/20261004090000_lister_marketing_mvp.sql');
const previous=original.slice(original.indexOf('create or replace function public.admin_lister_marketing')).trim();
const current=read('supabase/migrations/20261004231152_admin_marketing_generated_at.sql');
const definition=current.slice(current.indexOf('create or replace function public.admin_lister_marketing')).trim();
assert.equal(definition,previous.replace('return result;',"return result || jsonb_build_object('generated_at', clock_timestamp());"));
assert.match(definition,/private\.is_admin\(\(select auth\.uid\(\)\)\)/);
assert.match(definition,/security definer set search_path=''/);
assert.match(definition,/from public,anon/);
assert.match(definition,/to authenticated/);
assert.equal((definition.match(/limit 5001/g)||[]).length,2);
assert.match(definition,/old_status is distinct from 'active'/);
assert.ok(definition.indexOf('select distinct on (entity_id)')<definition.indexOf('where first_active.created_at>=p_from'));
const predicate=read('supabase/migrations/20260922014919_stage77_admin_mfa.sql');
assert.match(predicate,/auth\.jwt\(\)->>'aal'/);
assert.match(predicate,/= 'aal2'/);
assert.match(predicate,/exists\(select 1 from public.admin_users where user_id=p_user\)/);
console.log('PASS: migration is additive only; signature, grants, security, AAL2 membership predicate, independent limits, null-safe prior status and full-history-first query are preserved. This static test does not execute SQL; see the separate database run evidence.');
const optimized=read('supabase/migrations/20261005003252_admin_marketing_property_first_once.sql');
const optDefinition=optimized.slice(optimized.indexOf('create or replace function public.admin_lister_marketing')).trim();
const propertyExpression=definition.match(/first_active.created_at=\([\s\S]*?\) as is_first_property_publication/)[0];
const reverted=optDefinition.replace(/      left join \(\n        select other_r.property_id,[\s\S]*?\) property_first on property_first.property_id=p.id\n/,'').replace('first_active.created_at=property_first.first_at as is_first_property_publication',propertyExpression);
assert.equal(reverted,definition,'optimization changes only property-level calculation');
const reverse=read('docs/rollback/admin-marketing-property-first-once.sql');
assert.equal(reverse.slice(reverse.indexOf('create or replace function public.admin_lister_marketing')).trim(),definition,'reverse retains the exact generated_at-capable function');
console.log('PASS: focused optimization and exact generated_at-preserving reverse migration');
