const {test,expect}=require('@playwright/test');
const APP=process.env.VACANCY_E2E_URL||'http://127.0.0.1:4183';
async function boot(page){
 await page.route('**/rest/v1/**',r=>r.fulfill({status:200,contentType:'application/json',body:'[]'}));
 await page.route('**/auth/v1/**',r=>r.fulfill({status:401,contentType:'application/json',body:'{}'}));
 await page.goto(APP+'/#home');await page.waitForFunction(()=>booting===false);
 await page.evaluate(()=>{currentUser={id:'synthetic-owner'};VACANCY_BACKEND.myProperties=async()=>[];VACANCY_BACKEND.myVacancies=async()=>[];VACANCY_BACKEND.activeVacancies=async()=>[];refreshVacancies=async()=>{};optimiseListingImages=async files=>[...files];window.__toasts=[];toast=text=>window.__toasts.push(text);window.__fixture={id:'v1',roomId:'r1',propertyId:'p1',privateName:'Private A1',region:'Nairobi',city:'Nairobi',locality:'Westlands',marketCode:'KE',country:'Kenya',address:'Private road',publicLatitude:-1.2,publicLongitude:36.8,propertyType:'Apartment',parkingSpaces:0,waterAvailable:true,electricityAvailable:true,securityAvailable:true,internetAvailable:false,smokingAllowed:false,petsConsidered:false,household:'Quiet',unitType:'Studio',roomName:'Public title',rentAmount:10000,rentCurrency:'KES',rentPeriod:'month',deposit:10000,availableFrom:null,minimumStayWeeks:4,maxOccupants:1,furnished:false,ensuite:false,billsIncluded:false,smokingAllowedOverride:null,petsConsideredOverride:null,description:'A studio',unitDetails:{parkingSpaces:2,amenities:[{label:'Balcony',icon:'balcony'}],utilities:[{label:'Solar power',icon:'bolt'}],rules:[{label:'Smoking',allowed:false}]},media:[1,2,3].map(n=>({id:'m'+n,url:'data:image/gif;base64,R0lGODlhAQABAAAAACw=',storage_path:'photo'+n+'.jpg'}))};VACANCY_BACKEND.listingForEdit=async()=>window.__fixture;});
}
async function edit(page){await boot(page);await page.evaluate(async()=>{history.replaceState(null,'','#edit/v1');await renderEdit('v1')});await expect(page.locator('#listingForm')).toHaveAttribute('data-edit-vacancy','v1');}
async function submit(page){await page.locator('#listingForm').evaluate(form=>form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));await expect(page.locator('#listingForm')).not.toHaveAttribute('data-publishing','true');}
test('edit sends one complete DB transaction and no uploads when DB rejects',async({page})=>{
 await edit(page);await page.locator('.journey-next').click();await page.locator('.unit-name-input').fill('');
 await page.evaluate(()=>{window.__db=[];window.__uploads=[];VACANCY_BACKEND.updateListingAtomic=async(...args)=>{window.__db.push(args);throw new Error('Synthetic transaction failed')};VACANCY_BACKEND.uploadListingImages=async(...args)=>window.__uploads.push(args)});
 await page.locator('.journey-next').click();await submit(page);
 expect(await page.evaluate(()=>window.__db.length)).toBe(1);expect(await page.evaluate(()=>window.__db[0][3])).toBe('');expect(await page.evaluate(()=>window.__uploads)).toEqual([]);expect(await page.evaluate(()=>window.__toasts.at(-1))).toBe('Synthetic transaction failed');await expect(page.locator('#listingForm')).toBeVisible();
});
test('photo retries and reselection retain a stable operation key',async({page})=>{
 await edit(page);await page.locator('.journey-next').click();
 await page.evaluate(()=>{appendPhotoFiles(document.querySelector('.unit-editor input[type=file]'),[new File(['photo'],'extra.jpg',{type:'image/jpeg',lastModified:1})]);window.__keys=[];VACANCY_BACKEND.updateListingAtomic=async()=>{};VACANCY_BACKEND.uploadListingImages=async(_id,_files,key)=>{window.__keys.push(key);throw new Error('Synthetic photo failure')}});
 await page.locator('.journey-next').click();await submit(page);await submit(page);
 let keys=await page.evaluate(()=>window.__keys);expect(keys).toHaveLength(2);expect(keys[0]).toBe(keys[1]);expect(await page.evaluate(()=>window.__toasts.at(-1))).toContain('Listing details saved');
 await page.evaluate(()=>{const input=document.querySelector('.unit-editor input[type=file]');photoSelections.set(input,[new File(['reselected bytes'],'extra.jpg',{type:'image/jpeg',lastModified:1})]);renderPhotoSelection(input)});await submit(page);keys=await page.evaluate(()=>window.__keys);expect(keys).toHaveLength(3);expect(keys[2]).toBe(keys[1]);
});
test('existing-listing duplicate retains private name and full options but clears photos',async({page})=>{
 await boot(page);await page.evaluate(()=>beginVacancyDuplicate('v1'));await page.getByRole('button',{name:'New property'}).click();const form=page.locator('#listingForm');await expect(form).toBeVisible();await expect(form.locator('.unit-name-input')).toHaveValue('Private A1');const details=await form.locator('[data-base-name=unitDetails]').inputValue();expect(JSON.parse(details)).toMatchObject({parkingSpaces:2,amenities:[{label:'Balcony'}],utilities:[{label:'Solar power'}],rules:[{label:'Smoking',allowed:false}]});expect(await page.evaluate(()=>selectedPhotoFiles(document.querySelector('.unit-editor input[type=file]')).length)).toBe(0);
});

test('partial upload reconciles six existing plus A to seven tiles and retries only B after reselection',async({page})=>{
 await boot(page);await page.evaluate(async()=>{window.__fixture.media=[...window.__fixture.media,...[4,5,6].map(n=>({id:'m'+n,url:'data:image/gif;base64,R0lGODlhAQABAAAAACw=',storage_path:'photo'+n+'.jpg'}))];history.replaceState(null,'','#edit/v1');await renderEdit('v1')});await page.locator('.journey-next').click();
 await page.evaluate(()=>{const make=name=>new File([name],name,{type:'image/jpeg',lastModified:123});appendPhotoFiles(document.querySelector('.unit-editor input[type=file]'),[make('A.jpg'),make('B.jpg')]);window.__batches=[];VACANCY_BACKEND.updateListingAtomic=async()=>{};VACANCY_BACKEND.uploadListingImages=async(_id,files)=>{window.__batches.push(files.map(f=>f.name));if(window.__batches.length===1){const media={id:'new-A',storage_path:'new-A.jpg',url:'data:image/gif;base64,R0lGODlhAQABAAAAACw='},error=new Error('B upload failed');error.completedMedia=[{index:0,media}];error.currentMedia=[...window.__fixture.media,media];throw error}throw new Error('Keep retry visible')};});
 await page.locator('.journey-next').click();await submit(page);await expect(page.locator('.edit-existing-photo')).toHaveCount(7);expect(await page.evaluate(()=>selectedPhotoFiles(document.querySelector('.unit-editor input[type=file]')).map(f=>f.name))).toEqual(['B.jpg']);
 await page.evaluate(()=>{const input=document.querySelector('.unit-editor input[type=file]');photoSelections.set(input,['B.jpg','A.jpg'].map(name=>new File([name],name,{type:'image/jpeg',lastModified:123})));renderPhotoSelection(input)});await submit(page);expect(await page.evaluate(()=>window.__batches)).toEqual([['A.jpg','B.jpg'],['B.jpg']]);
});
test('legacy duplicate preserves scalar flags and matching structured amenities',async({page})=>{
 await boot(page);await page.evaluate(()=>{window.__fixture.unitDetails={};window.__fixture.furnished=true;window.__fixture.ensuite=false;return beginVacancyDuplicate('v1')});await page.getByRole('button',{name:'New property'}).click();const form=page.locator('#listingForm');await expect(form.locator('[data-base-name=furnished]')).toHaveValue('true');await expect(form.locator('[data-base-name=ensuite]')).toHaveValue('false');expect(JSON.parse(await form.locator('[data-base-name=unitDetails]').inputValue()).amenities).toContainEqual({label:'Furnished',icon:'furnished'});
});
