const {test,expect}=require('@playwright/test');
const APP=process.env.VACANCY_E2E_URL||'http://127.0.0.1:4173';
async function open(page){await page.route('**/rest/v1/vacancies?**',route=>route.fulfill({status:200,contentType:'application/json',body:'[]'}));await page.goto(`${APP}/#home`);await page.waitForFunction(()=>booting===false&&typeof card==='function')}
const vacancy=(id='v1',overrides={})=>({id,rentAmount:24000,rentCurrency:'KES',rentPeriod:'month',deposit:12000,updatedAt:new Date(Date.now()-2*60*1000).toISOString(),room:{id:'r1',name:'Studio in Kilimani',roomType:'Studio',media:[{url:'one.jpg'},{url:'two.jpg'},{url:'three.jpg'}]},property:{id:'p1',suburb:'Kilimani',city:'Nairobi',country:'Kenya',parkingSpaces:1,securityAvailable:true,internetAvailable:false},owner:{id:'o1'},...overrides});

test('cards use relative freshness, slash image count, location-first order and neutral deposit',async({page})=>{await open(page);const result=await page.evaluate(v=>{document.querySelector('#cards').innerHTML=card(v);bindCards();const cardNode=document.querySelector('.listing-card'),style=getComputedStyle(cardNode.querySelector('.deposit-card-pill'));return {text:cardNode.innerText,counter:cardNode.querySelector('.gallery-counter').textContent.trim(),fresh:cardNode.querySelector('.fresh').textContent,depositColor:style.color,order:[...cardNode.querySelector('.card-body').children].map(node=>node.className)}} ,vacancy());expect(result.counter).toBe('1/3');expect(result.fresh).toBe('2 mins ago');expect(result.text.replace(/\s+/g,' ')).toMatch(/Dep(?:osit|\.) KSh 12,000/);expect(result.depositColor).toBe('rgb(24, 24, 27)');expect(result.order[0]).toContain('listing-location');expect(result.order[1]).toBe('')});

test('gallery counter advances on horizontal swipe position',async({page})=>{await open(page);await page.evaluate(v=>{document.querySelector('#cards').innerHTML=card(v);bindCards();const gallery=document.querySelector('[data-gallery]');gallery.scrollLeft=gallery.scrollWidth;gallery.dispatchEvent(new Event('scroll'))},vacancy());await expect(page.locator('.gallery-counter')).toHaveText('3/3');await expect(page.locator('.gallery-counter')).toHaveAttribute('aria-label','Image 3 of 3')});

test('temporary sort is removed while result wording stays short',async({page})=>{await open(page);await page.evaluate(rows=>{vacancies=rows;renderHome()},[vacancy('high',{rentAmount:50000}),vacancy('low',{rentAmount:10000})]);await expect(page.locator('.sort-control')).toHaveCount(0);await expect(page.locator('#resultCount')).toHaveText('2 vacancies found');await expect(page.locator('#vacancyTourButton')).toBeVisible()});

test('double submit is locked before the first publish finishes',async({page})=>{await open(page);const calls=await page.evaluate(async()=>{currentUser={id:'owner'};VACANCY_BACKEND.myProperties=async()=>[];VACANCY_BACKEND.myVacancies=async()=>[];let release,createCalls=0;const pending=new Promise(resolve=>release=resolve);VACANCY_BACKEND.createListing=async()=>{createCalls++;await pending;return'v-new'};VACANCY_BACKEND.listingForEdit=async()=>({propertyId:'p-new'});VACANCY_BACKEND.activeVacancies=async()=>[];await renderList();const form=document.querySelector('#listingForm');form.querySelectorAll('[required]').forEach(input=>{if(input.type==='date')input.value='2026-10-01';else if(input.type==='number')input.value='1';else input.value='Test'});form.elements.publicLatitude.value='-1.28';form.elements.publicLongitude.value='36.82';form.requestSubmit();form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await new Promise(resolve=>setTimeout(resolve,20));const during={calls:createCalls,busy:form.dataset.publishing};release();await new Promise(resolve=>setTimeout(resolve,80));return during});expect(calls.calls).toBe(1);expect(calls.busy).toBe('true')});

test('account profile is aligned and exposes optional contact fields without false verification',async({page})=>{await open(page);await page.evaluate(async()=>{currentUser={id:'member',email:'member@example.com',user_metadata:{}};VACANCY_BACKEND.profile=async()=>({display_name:'Taylor',phone_number:'+61400000000',whatsapp_number:'',phone_verified:false});VACANCY_BACKEND.adminOverview=async()=>({error:'admin required'});await renderAccount()});await expect(page.locator('.account-identity h1')).toHaveText('Taylor');await expect(page.locator('[name="phoneNumber"]')).toHaveValue('+61400000000');await expect(page.locator('.profile-form')).toContainText('Not verified');await expect(page.locator('.account-tier')).toHaveText('Member')});

test('edit view gives owners view, reorder and delete controls for uploaded images',async({page})=>{await open(page);await page.evaluate(async()=>{currentUser={id:'owner'};const item={id:'m1',storage_path:'owner/r1/one.jpg',url:'https://example.com/one.jpg'};VACANCY_BACKEND.listingForEdit=async()=>({id:'v1',roomId:'r1',propertyId:'p1',media:[item],region:'Nairobi',city:'Nairobi',locality:'Kilimani',postal:'',marketCode:'KE',country:'Kenya',address:'Road',publicLatitude:-1.2,publicLongitude:36.8,propertyType:'Apartment',parkingSpaces:0,waterAvailable:true,electricityAvailable:true,securityAvailable:true,internetAvailable:false,smokingAllowed:false,petsConsidered:false,household:'',unitType:'Studio',roomName:'Studio',rentAmount:10000,rentCurrency:'KES',rentPeriod:'month',deposit:'',availableFrom:'2026-10-01',minimumStayWeeks:'',maxOccupants:1,furnished:false,ensuite:false,billsIncluded:false,smokingAllowedOverride:null,petsConsideredOverride:null,description:''});await renderEdit('v1')});await expect(page.locator('.media-manager img')).toHaveCount(1);await expect(page.getByRole('button',{name:'View'})).toBeVisible();await expect(page.getByRole('button',{name:'Delete'})).toBeVisible();await expect(page.locator('[name="household"]')).not.toHaveAttribute('required','')});

test('enquiry offers editable quick questions',async({page})=>{await open(page);await page.evaluate(v=>{currentUser={id:'renter'};vacancies=[v];renderEnquire(v.id)},vacancy());await page.getByRole('button',{name:'Can I arrange a viewing?'}).click();await expect(page.locator('#enquiryForm [name="message"]')).toHaveValue('Can I arrange a viewing?')});

test('unread messages fill the inbox icon and show a count',async({page})=>{await open(page);await page.evaluate(async()=>{currentUser={id:'me'};VACANCY_BACKEND.conversations=async()=>[{id:'c1',conversation_members:[{user_id:'me',last_read_at:'2026-09-09T09:00:00Z'}],messages:[{id:'m1',sender_id:'other',created_at:'2026-09-09T10:00:00Z'}]}];renderHome();await new Promise(resolve=>setTimeout(resolve,30))});await expect(page.locator('.mobile-nav [data-nav="messages"] .unread-badge')).toHaveText('1');await expect(page.locator('.mobile-nav [data-nav="messages"]')).toHaveClass(/has-unread/)});

test('find view keeps the shared footer and has no horizontal page overflow',async({page})=>{await open(page);await page.evaluate(rows=>{vacancies=rows;renderHome()},[vacancy('one'),vacancy('two',{room:{id:'r2',name:'Two bedroom',roomType:'2 bedroom',media:[{url:'one.jpg'}]}})]);await expect(page.locator('.site-footer')).toBeVisible();const bounds=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,page:document.documentElement.scrollWidth,body:document.body.scrollWidth}));expect(bounds.page).toBeLessThanOrEqual(bounds.viewport);expect(bounds.body).toBeLessThanOrEqual(bounds.viewport)});
