const {test,expect}=require('@playwright/test');
const APP=process.env.VACANCY_E2E_URL||'http://127.0.0.1:4173';

async function open(page){await page.route('**/rest/v1/vacancies?**',route=>route.fulfill({status:200,contentType:'application/json',body:'[]'}));await page.goto(`${APP}/#home`);await page.waitForFunction(()=>booting===false&&typeof renderList==='function')}
const property=(id,title)=>({id,title,managerNickname:title,locality:'Kasarani',city:'Nairobi',marketCode:''});
const vacancy=(id,status,propertyId)=>({id,status,rent_amount:12000,rent_currency:'KES',rent_period:'month',rooms:{id:`room-${id}`,name:`Unit ${id}`,properties:{id:propertyId,title:`Property ${propertyId}`,suburb:'Kasarani',city:'Nairobi',country:'Kenya'}}});

test('property chooser excludes properties whose listings are only archived or removed',async({page})=>{await open(page);await page.evaluate(async({properties,vacancies})=>{currentUser={id:'owner'};VACANCY_BACKEND.myProperties=async()=>properties;VACANCY_BACKEND.myVacancies=async()=>vacancies;await renderList()},{properties:[property('live','Live property'),property('old','Old property')],vacancies:[vacancy('one','active','live'),vacancy('two','archived','old')]});await page.getByRole('button',{name:'Studio',exact:true}).click();await page.getByRole('button',{name:'Existing property'}).click();await expect(page.getByRole('button',{name:/Live property/})).toBeVisible();await expect(page.getByRole('button',{name:/Old property/})).toHaveCount(0)});

test('listing address uses at most two distinct public levels',async({page})=>{await open(page);const location=await page.evaluate(()=>{const v={id:'one',rentAmount:12000,rentCurrency:'KES',rentPeriod:'month',updatedAt:'2026-09-09',room:{name:'Studio',roomType:'Studio',media:[]},property:{suburb:'Nairobi',city:'Nairobi',state:'Nairobi County',country:'Kenya',parkingSpaces:0},owner:{id:'owner'}};return {value:listingLocation(v),markup:card(v)}});expect(location.value).toBe('Nairobi');expect(location.markup).toContain('Nairobi');expect(location.markup).toContain('<h3>Studio</h3>');expect(location.markup).not.toContain('Nairobi, Nairobi')});

test('find controls and images retain fixed geometry with long result text',async({page},testInfo)=>{await open(page);await page.evaluate(()=>{document.querySelector('#resultCount').textContent='123,456 current vacancies within an exceptionally long distance label'});const result=await page.evaluate(()=>{const toolbar=document.querySelector('.listing-toolbar'),filter=document.querySelector('.results-filter-action'),view=document.querySelector('.view-switch'),search=document.querySelector('.map-search-field input'),area=document.querySelector('#searchArea');return {overflow:toolbar.scrollWidth-toolbar.clientWidth,filterRight:Math.round(filter.getBoundingClientRect().right),viewRight:Math.round(view.getBoundingClientRect().right),viewport:innerWidth,searchSize:getComputedStyle(search).fontSize,placeholderSize:getComputedStyle(search,'::placeholder').fontSize,areaColor:getComputedStyle(area).color}});expect(result.overflow).toBeLessThanOrEqual(1);expect(result.filterRight).toBeLessThan(result.viewRight);expect(result.viewRight).toBeLessThanOrEqual(result.viewport);expect(result.searchSize).toBe(testInfo.project.name.includes('mobile')?'16px':'13px');expect(result.placeholderSize).toBe(testInfo.project.name.includes('mobile')?'12px':'11px');expect(result.areaColor).toBe('rgb(255, 255, 255)')});

test('admin can switch live daily metrics without moving control structure',async({page})=>{await open(page);await page.evaluate(async()=>{currentUser={id:'admin'};VACANCY_BACKEND.adminDashboard=async()=>({users_total:4,properties:2,units:3,active_listings:2,open_reports:0,oldest_report_hours:0,enquiries_7d:1,listings_7d:2,errors_24h:0});VACANCY_BACKEND.adminSearch=async()=>({users:[],listings:[]});VACANCY_BACKEND.adminReports=async()=>[];VACANCY_BACKEND.adminAuditLog=async()=>[];VACANCY_BACKEND.adminDailyMetrics=async(metric,days)=>({metric,days:Number(days),total:3,series:[{date:'2026-09-08',value:1},{date:'2026-09-09',value:2}]});await renderAdmin()});await expect(page.getByRole('heading',{name:'Activity'})).toBeVisible();await expect(page.locator('.metric-column')).toHaveCount(2);await page.locator('#adminMetric').selectOption('images');await expect(page.locator('.metric-total')).toContainText('images uploaded')});

test('lister can begin with photos while the same draft keeps the guided flow',async({page})=>{await open(page);await page.evaluate(async()=>{currentUser={id:'owner'};VACANCY_BACKEND.myProperties=async()=>[];VACANCY_BACKEND.myVacancies=async()=>[];await renderList();const input=document.querySelector('input[type=file]');input.addEventListener('click',event=>{event.preventDefault();window.__photoPickerOpened=true})});await page.getByRole('button',{name:'Studio',exact:true}).click();await page.getByRole('button',{name:'New property'}).click();await page.getByRole('button',{name:'Add photos first'}).click();expect(await page.evaluate(()=>window.__photoPickerOpened)).toBeTruthy();await expect(page.locator('input[type=file]').locator('xpath=ancestor::details[contains(@class,"composer-section")]')).toHaveAttribute('open','')});
