const {test,expect}=require('@playwright/test');
const APP=process.env.VACANCY_E2E_URL||'http://127.0.0.1:4173';

async function openListing(page){
  await page.route('**/rest/v1/vacancies?**',route=>route.fulfill({status:200,contentType:'application/json',body:'[]'}));
  await page.goto(`${APP}/#home`);
  await page.waitForFunction(()=>booting===false);
  await page.evaluate(async()=>{currentUser={id:'owner'};VACANCY_BACKEND.myProperties=async()=>[];VACANCY_BACKEND.myVacancies=async()=>[];await renderList()});
}

test('the map control stays inside the map and a new pin replaces stale address fields',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await openListing(page);
  await page.locator('[data-listing-type=Residential]').click();
  await page.locator('[data-preset=Room]').click();
  await page.getByRole('button',{name:'New property'}).click();
  const form=page.locator('#listingForm');
  const control=form.getByRole('button',{name:'Use current location'});
  await expect(control).toBeVisible();
  expect(await control.evaluate(button=>button.parentElement.parentElement.contains(document.querySelector('#newPropertyMap')))).toBe(true);
  let lookups=0;
  await page.route('**/api/reverse-geocode?**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(++lookups===1
    ? {country:'Kenya',region:'Nairobi',city:'Nairobi',locality:'Westlands',landmark:'Mall',postal:'00100',address:'First Road'}
    : {country:'Kenya',region:'Mombasa',city:'Mombasa',locality:'Nyali',address:'Second Road'})}));
  await page.evaluate(()=>document.querySelector('#newPropertyMap')._vacancySetLocation(-1.26,36.8,true));
  await expect(form.locator('[name=landmark]')).toHaveValue('Mall');
  await page.evaluate(()=>document.querySelector('#newPropertyMap')._vacancySetLocation(-4.04,39.7,true));
  await expect(form.locator('[name=city]')).toHaveValue('Mombasa');
  await expect(form.locator('[name=landmark]')).toHaveValue('');
  await expect(form.locator('[name=postal]')).toHaveValue('');
});

test('active mobile destination keeps its icon outlined and orange',async({page})=>{
  await openListing(page);
  await page.evaluate(()=>nav('saved'));
  const saved=page.locator('.mobile-nav [data-nav=saved]');
  await expect(saved).toHaveAttribute('aria-current','page');
  const appearance=await saved.locator('svg').evaluate(svg=>({fill:getComputedStyle(svg).fill,stroke:getComputedStyle(svg).stroke}));
  expect(appearance.fill).toBe('none');
  expect(appearance.stroke).not.toBe('none');
});

test('mobile listing starts at the top and guides the existing form through five stages',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await openListing(page);
  await expect(page.locator('.mobile-nav [data-nav="list"]')).toHaveCount(1);
  await expect(page.locator('.topbar .list-action')).toBeHidden();
  const navCenters=await page.evaluate(()=>{const nav=document.querySelector('.mobile-nav').getBoundingClientRect(),list=document.querySelector('.mobile-nav [data-nav=list]').getBoundingClientRect();return [nav.left+nav.width/2,list.left+list.width/2]});
  expect(Math.abs(navCenters[0]-navCenters[1])).toBeLessThan(2);
  await expect(page.locator('.mobile-nav [data-nav="list"] svg')).toHaveAttribute('viewBox','0 0 24 24');
  await expect(page.locator('.listing-home-preset')).toBeHidden();
  await page.locator('[data-listing-type=Residential]').click();
  await expect(page.locator('.listing-home-preset')).toBeVisible();
  await page.locator('[data-preset=Room]').click();
  await expect(page.locator('.selected-home-pill')).toHaveText('Room');
  await expect(page.locator('.selected-home-pill')).toBeVisible();
  await page.getByRole('button',{name:'New property'}).click();
  const form=page.locator('#listingForm');
  await expect(form).toHaveAttribute('data-journey-step','0');
  await expect(page.locator('.listing-journey-rail')).toHaveCount(0);
  await expect(page.locator('.listing-journey-page > .page-back')).toBeHidden();
  await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBeLessThan(5);
  await expect(page.locator('.listing-top-stepper')).toBeHidden();
  await expect(page.locator('.journey-current-title')).toHaveText('Location');
  await expect(page.locator('#newPropertyMap')).toBeVisible();
  await expect(page.locator('.property-media-pool')).toBeHidden();
  await form.locator('.journey-next').click();
  await expect(form).toHaveAttribute('data-journey-step','0');
  await page.evaluate(()=>{const form=document.querySelector('#listingForm');for(const [key,value] of Object.entries({region:'Nairobi',city:'Nairobi',locality:'Westlands',address:'Example Road'}))form.elements[key].value=value;form.querySelector('#newPropertyMap')._vacancySetLocation(-1.26,36.8,false)});
  await form.locator('.journey-next').click();
  await expect(form).toHaveAttribute('data-journey-step','1');
  await expect(page.locator('.journey-current-title')).toHaveText('Property details');
  await expect(page.locator('.property-media-pool')).toBeHidden();
  await expect(form.locator('.journey-stage-heading .journey-back')).toHaveText('←');
  await expect(form.locator('.save-draft-action')).toBeHidden();
  await expect(page.locator('.vacancy-manager-head')).toBeHidden();
  await expect(page.locator('.site-footer')).toBeHidden();
  await expect(page.locator('.mobile-nav')).toBeHidden();
  await expect(form.locator('[name=propertyTitle]')).not.toHaveAttribute('required');
  await form.locator('.journey-next').click();
  await expect(form).toHaveAttribute('data-journey-step','2');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBe(0);
});

test('property photos flow into the unit and a complete listing can reach publish',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await openListing(page);
  await page.locator('[data-listing-type=Residential]').click();
  await page.locator('[data-preset=Room]').click();
  await page.getByRole('button',{name:'New property'}).click();
  const form=page.locator('#listingForm');
  await page.evaluate(()=>{const form=document.querySelector('#listingForm');for(const [key,value] of Object.entries({region:'Nairobi',city:'Nairobi',locality:'Westlands',address:'Example Road'}))form.elements[key].value=value;form.querySelector('#newPropertyMap')._vacancySetLocation(-1.26,36.8,false)});
  await form.locator('.journey-next').click();
  await expect(form).toHaveAttribute('data-journey-step','1');
  await expect(form.locator('[name="propertyTitle"]')).toHaveValue('');
  await expect(form.locator('.property-media-pool')).toBeHidden();
  await form.locator('.journey-next').click();
  await expect(form).toHaveAttribute('data-journey-step','2');
  await expect(form.locator('.journey-current-title')).toHaveText('Units');
  await expect(form.locator('.property-media-pool')).toBeVisible();
  await form.locator('.journey-next').click();
  await expect(form).toHaveAttribute('data-journey-step','2');
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScL/nwAAAABJRU5ErkJggg==','base64');
  await form.locator('.property-media-input').setInputFiles([1,2,3].map(number=>({name:`photo${number}.png`,mimeType:'image/png',buffer:png})));
  await expect(form.locator('.property-media-grid img')).toHaveCount(3);
  await form.locator('.journey-next').click();
  await expect(form).toHaveAttribute('data-journey-step','3');
  await form.locator('[data-base-name="rentAmount"]').fill('25000');
  await form.locator('.journey-next').click();
  await expect(form).toHaveAttribute('data-journey-step','4');
  await expect(form.locator('.listing-draft-preview')).toBeVisible();
  await expect(form.locator('.listing-draft-preview img')).toHaveCount(3);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBe(0);
  await page.evaluate(()=>{window.__published=[];VACANCY_BACKEND.createListing=async input=>{window.__published.push(input);return 'listing-test'};VACANCY_BACKEND.listingForEdit=async()=>({propertyId:'property-test'});VACANCY_BACKEND.uploadListingImages=async()=>[];VACANCY_BACKEND.setPropertyFeatures=async()=>{};VACANCY_BACKEND.trackEvent=()=>{};});
  await form.locator('.listing-submit-actions button.primary').click();
  await expect.poll(()=>page.evaluate(()=>window.__published.length)).toBe(1);
});

test('existing property keeps its identity and starts a unit without requesting a new map pin',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.route('**/rest/v1/vacancies?**',route=>route.fulfill({status:200,contentType:'application/json',body:'[]'}));
  await page.goto(`${APP}/#home`);await page.waitForFunction(()=>booting===false);
  await page.evaluate(async()=>{
    currentUser={id:'owner'};
    const property={id:'p1',title:'Westlands House',locality:'Westlands',city:'Nairobi',country:market().label,marketCode:marketCode,waterAvailable:true,electricityAvailable:true,securityAvailable:true,parkingSpaces:0};
    VACANCY_BACKEND.myProperties=async()=>[property];
    VACANCY_BACKEND.myVacancies=async()=>[{id:'v1',status:'active',rent_amount:25000,rent_currency:'KES',rent_period:'month',rooms:{name:'Existing room',properties:property}},{id:'v2',status:'archived',rent_amount:21000,rent_currency:'KES',rent_period:'month',rooms:{name:'Archived room',properties:property}}];
    await renderList();
  });
  await expect(page.locator('[data-edit]')).toHaveCount(2);
  await expect(page.locator('[data-edit] svg')).toHaveCount(2);
  await expect(page.locator('[data-edit]').first()).toHaveAttribute('aria-label','Edit listing');
  await page.locator('[data-listing-type=Residential]').click();
  await page.locator('[data-preset=Room]').click();
  await page.getByRole('button',{name:'Existing property'}).click();
  const form=page.locator('#existingListingForm');
  await expect(form).toHaveAttribute('data-journey-step','0');
  await expect(form.locator('#propertyChoice')).toHaveValue('p1');
  await form.locator('.journey-next').click();
  await expect(form).toHaveAttribute('data-journey-step','1');
  await expect(page.locator('.journey-current-title')).toHaveText('Property details');
  await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBeLessThan(5);
  await form.locator('.journey-back').click();
  await expect(form).toHaveAttribute('data-journey-step','0');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBe(0);
});

test('residential preset selects the matching apartment and unit types',async({page})=>{
  await openListing(page);
  await page.locator('[data-listing-type=Residential]').click();
  await expect(page.locator('.listing-home-preset')).toBeVisible();
  await page.locator('[data-preset="2 bedroom apartment"]').click();
  await page.getByRole('button',{name:'New property'}).click();
  await expect(page.locator('.listing-choice-breadcrumb')).toContainText('2 bedroom apartment');
  await expect(page.locator('#listingForm [name=propertyType]')).toHaveValue('Apartment');
  await expect(page.locator('#listingForm [data-base-name=unitType]')).toHaveValue('2 bedroom');
});

test('other property types continue directly without a room preset',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await openListing(page);
  await page.locator('[data-listing-type=House]').click();
  await expect(page.locator('.listing-home-preset')).toBeHidden();
  await page.getByRole('button',{name:'New property'}).click();
  await expect(page.locator('#listingForm [name=propertyType]')).toHaveValue('House');
  await expect(page.locator('.listing-journey-page > .page-back')).toBeHidden();
});

test('features are one-tap, parking is grouped, and the local draft is discarded in Your vacancies',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await openListing(page);
  await page.locator('[data-listing-type=House]').click();
  await page.getByRole('button',{name:'New property'}).click();
  const form=page.locator('#listingForm');
  await expect(form.locator('.listing-draft-status')).toHaveCount(0);
  await page.evaluate(()=>{const form=document.querySelector('#listingForm');for(const [key,value] of Object.entries({region:'Nairobi',city:'Nairobi',locality:'Westlands',address:'Example Road'}))form.elements[key].value=value;form.querySelector('#newPropertyMap')._vacancySetLocation(-1.26,36.8,false)});
  await form.locator('.journey-next').click();
  await form.locator('[name=propertyTitle]').fill('Garden House');
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScL/nwAAAABJRU5ErkJggg==','base64');
  await form.locator('.property-media-input').setInputFiles([1,2,3].map(number=>({name:'photo'+number+'.png',mimeType:'image/png',buffer:png})));
  await form.locator('.journey-next').click();
  await expect(form.locator('.journey-current-title')).toHaveText('Units');
  await expect(form.locator('.unit-toolbar .unit-name-input')).toHaveValue('Unit 1');
  const unitOrder=await form.locator('.unit-editor').first().evaluate(unit=>[...unit.children].filter(item=>item.matches('.unit-toolbar,label,.unit-features,.unit-utilities,.unit-rules,.advanced-unit-settings,.unit-photo-choices,.unit-delete')).map(item=>item.classList.contains('unit-toolbar')?'name':item.classList.contains('unit-features')?'amenities':item.classList.contains('unit-utilities')?'utilities':item.classList.contains('unit-rules')?'rules':item.classList.contains('advanced-unit-settings')?'advanced':item.classList.contains('unit-photo-choices')?'media':item.classList.contains('unit-delete')?'delete':item.querySelector('[data-base-name]')?.dataset.baseName));
  expect(unitOrder.filter(item=>item&&!['deposit','images'].includes(item))).toEqual(['name','unitType','roomName','description','amenities','utilities','rules','advanced','media','delete']);
  await form.locator('.unit-toolbar .unit-name-input').fill('Garden room');
  await expect(form.locator('.unit-editor').first().locator('[data-base-name=roomName]')).toHaveValue('Garden room');
  await expect(form.locator('.duplicate-unit-menu').first().locator('summary')).toHaveAttribute('aria-label','Duplicate unit');
  await expect(form.locator('.unit-editor').first().locator('.unit-delete')).toBeVisible();
  await page.evaluate(()=>{document.querySelector('.unit-editor [data-base-name=rentAmount]').value='24000';document.querySelector('.unit-editor [data-base-name=furnished]').value='true'});
  await form.locator('.duplicate-unit-menu').first().locator('summary').click();
  await form.locator('.duplicate-same-property').first().click();
  await expect(form.locator('.unit-editor')).toHaveCount(2);
  await expect(form.locator('.unit-editor').last().locator('[data-base-name=rentAmount]')).toHaveValue('24000');
  await expect(form.locator('.unit-editor').last().locator('[data-base-name=furnished]')).toHaveValue('true');
  await expect(form.locator('.unit-editor').last().locator('[data-base-name=roomName]')).toHaveValue('Garden room');
  await expect(form.locator('.unit-editor').last().locator('[data-base-name=roomName]')).toBeEditable();
  expect(await page.evaluate(()=>selectedPhotoFiles(document.querySelectorAll('.unit-editor input[type=file]')[1]).length)).toBe(3);
  await form.locator('.unit-editor').first().locator('.unit-delete').click();
  await expect(form.locator('.unit-editor')).toHaveCount(1);
  await form.locator('.add-unit').click();
  await expect(form.locator('.unit-editor')).toHaveCount(2);
  await expect(form.locator('.unit-editor').last().locator('.unit-name-input')).toHaveValue('Unit 2');
  await expect(form.locator('.unit-editor').last().locator('[data-base-name=rentAmount]')).toHaveValue('');
  await expect(form.locator('.unit-editor').last().locator('[data-base-name=furnished]')).toHaveValue('');
  expect(await page.evaluate(()=>selectedPhotoFiles(document.querySelectorAll('.unit-editor input[type=file]')[1]).length)).toBe(0);
  await form.locator('.unit-editor').last().locator('.advanced-unit-settings > summary').click();
  await form.locator('.unit-editor').last().locator('[aria-label="Increase maximum occupants"]') .click();
  await expect(form.locator('.unit-editor').last().locator('[data-base-name=maxOccupants]')).toHaveValue('2');
  await expect(form.locator('.unit-editor').last().locator('[data-base-name=roomName]')).toHaveValue('Unit 2');
  await form.locator('.unit-editor').last().locator('.unit-delete').click();
  await expect(form.locator('.unit-editor')).toHaveCount(1);
  await expect(form.locator('.property-features [name=parkingSpaces]')).toHaveCount(1);
  await expect(form.locator('.property-features .add-more-choice')).toHaveCount(0);
  await form.locator('.unit-features > summary').click();
  await form.locator('[data-feature=balcony]').click();
  await expect(form.locator('[name=customFeatures]')).toHaveValue('[{"label":"Balcony","icon":"balcony"}]');
  await form.locator('.add-feature-action').click();
  await form.locator('[aria-label="Your feature name"]').fill('Rooftop terrace');
  await expect(form.locator('[name=customFeatures]')).toHaveValue(/Rooftop terrace/);
  await form.locator('.journey-next').click();
  await expect.poll(()=>page.locator('#mine .local-draft-row').count()).toBe(1);
  await expect(page.locator('#mine .local-draft-row')).toContainText('Garden House');
  await expect(page.locator('#mine [data-resume-draft]')).toHaveAttribute('aria-label','Edit draft');
  await expect(page.locator('#mine [data-resume-draft] svg')).toBeHidden();
  await page.evaluate(()=>renderList());
  await expect(page.locator('#mine [data-resume-draft] svg')).toBeVisible();
  await page.locator('[data-listing-type=House]').click();
  await page.getByRole('button',{name:'New property'}).click();
  await expect(page.locator('#listingForm [data-feature=balcony]')).toHaveAttribute('aria-pressed','true');
  await expect(page.locator('#listingForm [aria-label="Your feature name"]')).toHaveValue('Rooftop terrace');
  await page.evaluate(()=>renderList());
  page.once('dialog',dialog=>dialog.accept());
  await page.locator('#mine [data-delete-draft]').click();
  await expect(page.locator('#mine .local-draft-row')).toHaveCount(0);
});

test('duplicate listing into a new property copies unit details but requires a new location and photos',async({page})=>{
  await page.route('**/rest/v1/vacancies?**',route=>route.fulfill({status:200,contentType:'application/json',body:'[]'}));
  await page.goto(`${APP}/#home`);await page.waitForFunction(()=>booting===false);
  await page.evaluate(async()=>{
    currentUser={id:'owner'};
    const property={id:'p1',title:'Original House',locality:'Westlands',city:'Nairobi',country:market().label,marketCode:marketCode,waterAvailable:true,electricityAvailable:true,securityAvailable:true,parkingSpaces:0};
    VACANCY_BACKEND.myProperties=async()=>[property];
    VACANCY_BACKEND.myVacancies=async()=>[{id:'v1',status:'active',rent_amount:25000,rent_currency:'KES',rent_period:'month',rooms:{name:'Original room',properties:property}}];
    VACANCY_BACKEND.listingForEdit=async()=>({id:'v1',roomId:'r1',propertyId:'p1',roomName:'Original room',unitType:'Studio',rentAmount:25000,rentCurrency:'KES',rentPeriod:'month',deposit:5000,availableFrom:'2026-10-01',minimumStayWeeks:8,maxOccupants:2,furnished:true,ensuite:false,billsIncluded:false,description:'Bright room',smokingAllowedOverride:null,petsConsideredOverride:null,media:[{id:'m1'}]});
    await renderList();
  });
  await page.locator('#mine [data-duplicate]').click();
  await expect(page.locator('.duplicate-destination-note')).toContainText('Original room');
  await page.getByRole('button',{name:'New property'}).click();
  const form=page.locator('#listingForm');
  await expect(form).toHaveAttribute('data-journey-step','0');
  await expect(form.locator('[data-base-name="roomName"]')).toHaveValue('Original room');
  await expect(form.locator('[data-base-name="rentAmount"]')).toHaveValue('25000');
  await expect(form.locator('[data-base-name="furnished"]')).toHaveValue('true');
  await expect(form.locator('[name="address"]')).toBeEmpty();
  await expect(form.locator('.property-media-grid img')).toHaveCount(0);
  await page.evaluate(()=>renderList());
  await page.locator('#mine [data-duplicate]').click();
  await page.getByRole('button',{name:'Existing property'}).click();
  const existing=page.locator('#existingListingForm');
  await expect(existing.locator('#propertyChoice')).toHaveValue('p1');
  await expect(existing.locator('[data-base-name="roomName"]')).toHaveValue('Original room');
  await expect(existing.locator('[data-base-name="deposit"]')).toHaveValue('5000');
  await expect(existing.locator('.property-media-grid img')).toHaveCount(0);
});
test('map selection fills the address and a changed address updates the pin',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.route('**/api/reverse-geocode?**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({address:'Example Road',formattedAddress:'Example Road, Westlands, Nairobi, Kenya',locality:'Westlands',city:'Nairobi',region:'Nairobi County',country:'Kenya'})}));
  await page.route('**/api/geocode?**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({lat:-1.29,lon:36.81,label:'Another Street, Nairobi, Kenya'})}));
  await openListing(page);
  await page.locator('[data-listing-type=House]').click();
  await page.getByRole('button',{name:'New property'}).click();
  const form=page.locator('#listingForm');
  await page.evaluate(()=>document.querySelector('#newPropertyMap')._vacancySetLocation(-1.26,36.8,true));
  await expect(form.locator('[name=address]')).toHaveValue('Example Road');
  await expect(form.locator('[name=locality]')).toHaveValue('Westlands');
  await expect(form).toHaveAttribute('data-journey-step','0');
  await form.locator('[name=address]').fill('Another Street');
  await expect(form.locator('[name=publicLatitude]')).toHaveValue('');
  await form.locator('[name=address]').press('Tab');
  await expect(form.locator('[name=publicLatitude]')).toHaveValue('-1.290');
  await form.locator('.journey-next').click();
  await expect(form).toHaveAttribute('data-journey-step','1');
  await expect(form.locator('.chosen-property-address')).toContainText('Westlands, Nairobi, Kenya');
  await expect(form.locator('.chosen-property-address')).not.toContainText('Example Road');
});
