const {test,expect}=require('@playwright/test');
const APP=process.env.VACANCY_E2E_URL||'http://127.0.0.1:4173';
const vacancy={id:'v1',rentAmount:24000,rentCurrency:'KES',rentPeriod:'month',deposit:12000,updatedAt:new Date().toISOString(),room:{id:'r1',name:'Studio',roomType:'Studio',furnished:null,ensuite:null,media:[]},property:{id:'p1',suburb:'Kilimani',city:'Nairobi',country:'Kenya',parkingSpaces:1,securityAvailable:true,internetAvailable:true,waterAvailable:true,electricityAvailable:true,publicLatitude:-1.2,publicLongitude:36.8},owner:{id:'o1'}};

async function open(page){await page.route('**/rest/v1/vacancies?**',route=>route.fulfill({status:200,contentType:'application/json',body:'[]'}));await page.goto(`${APP}/#home`);await page.waitForFunction(()=>booting===false&&typeof renderList==='function')}
async function composer(page){await open(page);await page.evaluate(async()=>{currentUser={id:'owner'};VACANCY_BACKEND.myProperties=async()=>[];VACANCY_BACKEND.myVacancies=async()=>[];await renderList()});await page.getByRole('button',{name:'Studio',exact:true}).click();await page.getByRole('button',{name:'New property'}).click();await expect(page.locator('#listingForm')).toBeVisible()}

test('listing cards use an outline pin and regular deposit weight',async({page})=>{await open(page);await page.evaluate(row=>{vacancies=[row];renderHome()},vacancy);const pin=page.locator('.listing-location use[href="#icon-location-pin"]').first(),deposit=page.locator('.deposit-card-pill').first();await expect(pin).toBeVisible();expect(await pin.evaluate(node=>getComputedStyle(node).fill)).toBe('none');expect(await deposit.evaluate(node=>getComputedStyle(node).fontWeight)).toMatch(/400|500/)});

test('sort sits immediately before filter with matching unboxed text',async({page})=>{await open(page);const result=await page.evaluate(()=>{const toolbar=document.querySelector('.listing-toolbar'),sort=toolbar.querySelector('.sort-control'),filter=toolbar.querySelector('.results-filter-action'),select=sort.querySelector('select');return{before:sort.nextElementSibling===filter,sortSize:getComputedStyle(select).fontSize,filterSize:getComputedStyle(filter).fontSize,border:getComputedStyle(select).borderTopWidth}});expect(result.before).toBeTruthy();expect(result.sortSize).toBe(result.filterSize);expect(result.border).toBe('0px')});

test('listing choice remains above the form and uses lighter centered boxes',async({page})=>{await composer(page);const result=await page.evaluate(()=>{const start=document.querySelector('.listing-start'),form=document.querySelector('#listingForm'),button=start.querySelector('[data-listing-type].selected');return{connected:start.isConnected,before:Boolean(start.compareDocumentPosition(form)&Node.DOCUMENT_POSITION_FOLLOWING),align:getComputedStyle(start).textAlign,weight:getComputedStyle(button).fontWeight,disabled:button.disabled}});expect(result).toEqual(expect.objectContaining({connected:true,before:true,align:'center',disabled:true}));expect(Number(result.weight)).toBeLessThanOrEqual(500)});

test('property utilities collapse and summarize selected common icons',async({page})=>{await composer(page);const utilities=page.locator('.property-utilities');await expect(utilities).not.toHaveAttribute('open','');await expect(utilities.locator('.utility-summary-icons .service-icon')).toHaveCount(3);await utilities.locator('summary').click();await utilities.getByRole('button',{name:'Change Internet / fibre'}).click();await expect(utilities.locator('.utility-summary-icons .service-icon')).toHaveCount(4)});

test('advanced property controls are closed at the bottom and property text is regular',async({page})=>{await composer(page);const section=page.locator('.composer-section').filter({has:page.locator('summary strong',{hasText:'Property details'})}),advanced=section.locator('.advanced-unit-settings').filter({hasText:'Advanced property settings'});await expect(advanced).not.toHaveAttribute('open','');const result=await section.evaluate(node=>{const body=node.querySelector('.composer-section-body'),advanced=[...body.querySelectorAll('.advanced-unit-settings')].find(item=>item.textContent.includes('Advanced property')),next=body.querySelector('.section-continue'),label=body.querySelector('label');return{lastBeforeContinue:advanced.nextElementSibling===next,labelWeight:getComputedStyle(label).fontWeight,overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth}});expect(result.lastBeforeContinue).toBeTruthy();expect(Number(result.labelWeight)).toBeLessThanOrEqual(500);expect(result.overflow).toBeLessThanOrEqual(1)});

test('optional facts start unknown and automatic title remains stable',async({page})=>{await composer(page);await page.locator('.listing-steps button').filter({hasText:'Listing'}).click();const furnished=page.locator('select[name="furnished"]'),ensuite=page.locator('select[name="ensuite"]'),title=page.locator('[name="roomName"]'),toggle=page.getByRole('button',{name:'Use manual listing title'});await expect(furnished).toHaveValue('');await expect(ensuite).toHaveValue('');await expect(title).toBeVisible();await expect(title).toHaveAttribute('readonly','');const position=()=>title.evaluate(node=>node.getBoundingClientRect().top+scrollY),before=await position();await toggle.click();await expect(title).not.toHaveAttribute('readonly','');await title.fill('My own title');await page.getByRole('button',{name:'Use automatic listing title'}).click();await expect(title).toHaveValue(/Studio/);const after=await position();expect(Math.abs(after-before)).toBeLessThan(2)});

test('add photos is a reachable square placeholder',async({page})=>{await composer(page);const button=page.getByRole('button',{name:'Add photos'}),box=await button.boundingBox();await expect(button.locator('svg')).toHaveCount(1);expect(Math.abs(box.width-box.height)).toBeLessThanOrEqual(8)});

test('backend preserves unknown furnished and ensuite states from persisted flags',async({page})=>{await open(page);const result=await page.evaluate(async()=>{const originalFetch=window.fetch;let requested='';window.fetch=async url=>{requested=String(url);return new Response(JSON.stringify([{id:'v-unknown',rent_amount:100,rent_currency:'KES',rent_period:'month',monthly_rent:100,deposit:null,bills_included:false,updated_at:new Date().toISOString(),status:'active',rooms:{id:'r-unknown',name:'Studio',unit_type:'Studio',furnished:false,ensuite:false,furnished_known:false,ensuite_known:false,max_occupants:1,media:[],properties:{id:'p-unknown',title:'Test',suburb:'Kilimani',city:'Nairobi',country:'Kenya',parking_spaces:0,pets_considered:false,smoking_allowed:false,water_available:true,electricity_available:true,security_available:false,internet_available:false,public_latitude:-1.2,public_longitude:36.8,owner_id:'o-unknown'}}}]),{status:200,headers:{'Content-Type':'application/json'}})};try{const rows=await VACANCY_BACKEND.activeVacancies();return{furnished:rows[0].room.furnished,ensuite:rows[0].room.ensuite,selectsKnown:requested.includes('furnished_known')&&requested.includes('ensuite_known')}}finally{window.fetch=originalFetch}});expect(result).toEqual({furnished:null,ensuite:null,selectsKnown:true})});
