const {test,expect}=require('@playwright/test');
const APP_URL=process.env.VACANCY_E2E_URL;
const vacancy=(about='')=>({id:'stage54-v',rentAmount:24000,rentCurrency:'KES',rentPeriod:'month',deposit:12000,billsIncluded:false,availableFrom:'2026-10-01',minimumStayWeeks:0,status:'active',room:{id:'r1',name:'Studio in Kilimani',roomType:'Studio',furnished:false,ensuite:false,maxOccupants:2,description:'Repeated copy should not appear.',media:[]},property:{id:'p1',title:'Acacia',suburb:'Kilimani',city:'Nairobi',state:'Nairobi',country:'Kenya',propertyType:'Apartment',parkingSpaces:1,petsConsidered:false,smokingAllowed:false,householdSummary:about,waterAvailable:true,electricityAvailable:true,securityAvailable:true,internetAvailable:false,publicLatitude:-1.29,publicLongitude:36.78},owner:{id:'o1',displayName:'Lister',bio:''}});
async function open(page){await page.route('**/rest/v1/vacancies?**',route=>route.fulfill({status:200,contentType:'application/json',body:'[]'}));await page.addInitScript(()=>localStorage.setItem('vacancy-market-v1','KE'));await page.goto(`${APP_URL}/#home`);await page.waitForFunction(()=>booting===false)}
async function detail(page,about=''){await open(page);await page.evaluate(v=>{history.replaceState(null,'',`#detail/${v.id}`);vacancies=[v];renderDetail(v.id)},vacancy(about))}
async function composer(page){await open(page);await page.evaluate(async()=>{currentUser={id:'owner'};const property={id:'p1',reference_code:'VAC-P-TEST',title:'Acacia',suburb:'Kilimani',city:'Nairobi',country:'Kenya'};VACANCY_BACKEND.myProperties=async()=>[{id:'p1',title:'Acacia',locality:'Kilimani',city:'Nairobi'}];VACANCY_BACKEND.myVacancies=async()=>[{id:'existing',reference_code:'VAC-L-TEST',status:'active',rent_amount:24000,rent_currency:'KES',rent_period:'month',rooms:{id:'r-existing',name:'Existing unit',properties:property}}];await renderList()});await page.getByRole('button',{name:'Studio',exact:true}).click();await page.getByRole('button',{name:'New property'}).click();await expect(page.locator('#listingForm')).toBeVisible()}

test('detail keeps price, deposit and enquire concise, without repeated facts',async({page})=>{await detail(page);await expect(page.locator('.breadcrumbs,.property-facts,.detail-hero~.split')).toHaveCount(0);await expect(page.locator('.deposit-pill')).toHaveText(/Deposit KSh 12,000/);await expect(page.locator('.detail-summary>.panel')).not.toContainText('Repeated copy');await expect(page.getByRole('button',{name:'Enquire'})).toBeVisible();await expect(page.getByRole('heading',{name:'About the property'})).toHaveCount(0)});
test('detail presents flat icon rows and anchors safety to the gallery',async({page})=>{await detail(page,'Quiet building.');const section=page.locator('.detail-flat-section').filter({hasText:'Utilities and access'});await expect(section.locator('details,select')).toHaveCount(0);await expect(section.getByText('No smoking allowed')).toBeVisible();await expect(section.locator('li .service-icon')).not.toHaveCount(0);await expect(page.getByRole('heading',{name:'About the property'})).toBeVisible();expect(await page.locator('#listingSafetyToggle').evaluate(n=>({parent:n.parentElement.className,position:getComputedStyle(n).position}))).toEqual({parent:'detail-gallery',position:'absolute'})});
test('listing composer uses icon location, advanced nickname and quantity controls',async({page})=>{await composer(page);await expect(page.getByRole('button',{name:'Back to properties'})).toHaveCount(0);await page.locator('.listing-steps button').nth(2).click();await expect(page.getByRole('button',{name:'Use current location'}).locator('svg')).toHaveCount(1);await page.locator('.listing-steps button').nth(0).click();await expect(page.locator('[name=propertyNickname]')).toBeHidden();await expect(page.locator('[name=parkingSpaces]').locator('xpath=..').getByRole('button')).toHaveCount(2);await page.locator('.listing-steps button').nth(1).click();const unit=page.locator('.composer-section[open]');await unit.locator('.advanced-unit-settings summary').click();await expect(unit.locator('[name=maxOccupants]')).toHaveAttribute('type','number');await expect(unit.locator('[name=maxOccupants]').locator('xpath=..').getByRole('button')).toHaveCount(2)});
test('accepted reverse-geocoded location closes and shows the chosen address',async({page})=>{await page.route('**/api/reverse-geocode?**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({formattedAddress:'10 Test Road, Kilimani',region:'Nairobi',city:'Nairobi',locality:'Kilimani',address:'10 Test Road'})}));await composer(page);await page.locator('.listing-steps button').nth(2).click();await page.evaluate(()=>document.querySelector('#newPropertyMap')._vacancySetLocation(-1.29,36.78,true));await page.getByRole('button',{name:'Use this location'}).click();await expect(page.locator('.composer-section').nth(2)).not.toHaveAttribute('open','');await expect(page.locator('.chosen-property-address')).toContainText('10 Test Road')});
test('filters are narrower, offer both units and hide More filters when expanded',async({page})=>{await open(page);await page.getByRole('button',{name:'Map tools'}).click();const filters=page.locator('#discoveryFilters');const widths=await filters.evaluate(n=>({filter:n.getBoundingClientRect().width,viewport:innerWidth}));expect(widths.filter).toBeLessThanOrEqual(widths.viewport*.81);await expect(filters.getByRole('button',{name:'KM'})).toBeVisible();await expect(filters.getByRole('button',{name:'MI'})).toBeVisible();await filters.getByText('More filters').click();await expect(filters.getByText('More filters')).toBeHidden()});
test('header and page back are transparent and compact',async({page})=>{await detail(page);const style=await page.locator('.topbar').evaluate(n=>({background:getComputedStyle(n).backgroundColor,blur:getComputedStyle(n).backdropFilter}));expect(style.background).toBe('rgba(0, 0, 0, 0)');expect(style.blur).toBe('none');const back=await page.locator('.page-back').boundingBox();expect(back.x).toBeGreaterThanOrEqual(4)});
