const {test,expect}=require('@playwright/test');
const APP=process.env.VACANCY_E2E_URL||'http://127.0.0.1:4173';
const vacancy={id:'v61',rentAmount:24000,rentCurrency:'KES',rentPeriod:'month',deposit:12000,updatedAt:new Date().toISOString(),room:{id:'r61',name:'Studio',roomType:'Studio',furnished:true,ensuite:false,media:[]},property:{id:'p61',suburb:'Kilimani',city:'Nairobi',country:'Kenya',parkingSpaces:1,securityAvailable:true,internetAvailable:true,waterAvailable:true,electricityAvailable:true,customFeatures:[{label:'Balcony',icon:'balcony'}],publicLatitude:-1.2,publicLongitude:36.8},owner:{id:'o61'}};

async function open(page){await page.route('**/rest/v1/vacancies?**',route=>route.fulfill({status:200,contentType:'application/json',body:'[]'}));await page.goto(`${APP}/#home`);await page.waitForFunction(()=>booting===false&&typeof renderList==='function')}
async function composer(page){await open(page);await page.evaluate(async()=>{currentUser={id:'owner'};VACANCY_BACKEND.myProperties=async()=>[];VACANCY_BACKEND.myVacancies=async()=>[];await renderList()});await page.getByRole('button',{name:'Studio',exact:true}).click();await page.getByRole('button',{name:'New property'}).click();await expect(page.locator('#listingForm')).toBeVisible()}

test('discovery keeps filter and view together without sort and compacts filter inputs',async({page})=>{await open(page);const toolbar=page.locator('.listing-toolbar');await expect(toolbar.locator('.sort-control')).toHaveCount(0);expect(await toolbar.evaluate(node=>node.querySelector('.results-filter-action').nextElementSibling===node.querySelector('.view-switch'))).toBeTruthy();await page.getByRole('button',{name:'Map tools'}).click();const field=page.locator('.discovery-filters input').first(),style=await field.evaluate(node=>({font:getComputedStyle(node).fontSize,padding:getComputedStyle(node).paddingTop}));expect(parseFloat(style.font)).toBeLessThanOrEqual(12);expect(parseFloat(style.padding)).toBeLessThanOrEqual(5)});

test('site typography uses a deliberate readable hierarchy',async({page})=>{await open(page);await page.evaluate(row=>{vacancies=[row];renderHome()},vacancy);await expect(page.locator('.listing-card h3').first()).toHaveCSS('font-weight','600');await expect(page.locator('.listing-card .price').first()).toHaveCSS('font-weight','700');await expect(page.locator('body')).toHaveCSS('font-weight','400')});

test('listing icons are theme-safe and unboxed while time and deposit pills stay balanced',async({page})=>{await open(page);await page.evaluate(row=>{vacancies=[row];renderHome()},vacancy);for(const [theme,color] of [['light','rgb(24, 24, 27)'],['dark','rgb(250, 250, 250)']]){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);const result=await page.locator('.listing-card').first().evaluate(card=>{const icon=card.querySelector('.service-card-pill'),heart=card.querySelector('.heart-action'),fresh=card.querySelector('.fresh'),deposit=card.querySelector('.deposit-card-pill');return{iconColor:getComputedStyle(icon).color,iconBg:getComputedStyle(icon).backgroundColor,heartBg:getComputedStyle(heart).backgroundColor,freshShadow:getComputedStyle(fresh).boxShadow,freshBg:getComputedStyle(fresh).backgroundColor,depositAlign:getComputedStyle(deposit).alignItems}});expect(result.iconColor).toBe(color);expect(result.iconBg).toBe('rgba(0, 0, 0, 0)');expect(result.heartBg).toBe('rgba(0, 0, 0, 0)');expect(result.freshShadow).toBe('none');expect(result.freshBg).toContain('0.5');expect(result.depositAlign).toBe('center')}});

test('listing progress is vertical and add-to choice remains highlighted',async({page})=>{await composer(page);const points=await page.locator('.listing-steps button').evaluateAll(nodes=>nodes.map(node=>node.getBoundingClientRect())),add=page.locator('[data-add-mode="new"]');expect(points.every((point,index)=>!index||point.y>points[index-1].y)).toBeTruthy();expect(Math.max(...points.map(x=>x.x))-Math.min(...points.map(x=>x.x))).toBeLessThan(2);await expect(add).toHaveClass(/selected/)});

test('property media pool previews, removes, and shares photos with the unit',async({page})=>{await composer(page);const input=page.locator('.property-media-input');await input.setInputFiles([{name:'front.jpg',mimeType:'image/jpeg',buffer:Buffer.from('front')},{name:'room.jpg',mimeType:'image/jpeg',buffer:Buffer.from('room')}]);await expect(page.locator('.property-media-grid figure')).toHaveCount(2);await expect(page.locator('.unit-photo-choices summary span')).toHaveText('2 selected');expect(await page.evaluate(()=>selectedPhotoFiles(document.querySelector('.unit-editor input[type="file"]')).length)).toBe(2);await page.locator('[data-remove-pool="0"]').click();await expect(page.locator('.property-media-grid figure')).toHaveCount(1);await expect(page.locator('.unit-photo-choices summary span')).toHaveText('1 selected')});

test('unit-only photos merge with shared photos and can be removed independently',async({page})=>{await composer(page);await page.locator('.property-media-input').setInputFiles({name:'shared.jpg',mimeType:'image/jpeg',buffer:Buffer.from('shared')});await page.locator('.unit-editor input[type="file"]').setInputFiles({name:'unit.jpg',mimeType:'image/jpeg',buffer:Buffer.from('unit')});await expect(page.locator('.unit-photo-choices summary span')).toHaveText('2 selected');await page.locator('.listing-steps button').nth(1).click();await page.locator('.unit-photo-choices summary').click();await expect(page.locator('.unit-extra-photo')).toContainText('unit.jpg');expect(await page.evaluate(()=>selectedPhotoFiles(document.querySelector('.unit-editor input[type="file"]')).map(file=>file.name))).toEqual(['shared.jpg','unit.jpg']);await page.locator('[data-remove-unit-photo="0"]').click();await expect(page.locator('.unit-photo-choices summary span')).toHaveText('1 selected');await expect(page.locator('.property-media-grid figure')).toHaveCount(1)});

test('advanced property and listing fields stay closed at their section bottoms',async({page})=>{await composer(page);const property=page.locator('.composer-section').filter({hasText:'Property details'}),unit=page.locator('.composer-section').filter({hasText:'Unit & availability'}),propertyAdvanced=property.locator('.advanced-unit-settings'),unitAdvanced=unit.locator('.advanced-unit-settings');await expect(propertyAdvanced).not.toHaveAttribute('open','');await expect(unitAdvanced).not.toHaveAttribute('open','');expect(await property.evaluate(node=>node.querySelector('.advanced-unit-settings').nextElementSibling.classList.contains('section-continue'))).toBeTruthy();expect(await unit.evaluate(node=>node.querySelector('.advanced-unit-settings').nextElementSibling.classList.contains('section-continue'))).toBeTruthy();for(const name of ['availableFrom','minimumStayWeeks','maxOccupants'])await expect(unitAdvanced.locator(`[data-base-name="${name}"], [name="${name}"]`)).toBeHidden();await expect(propertyAdvanced.locator('[name="household"]')).toBeHidden()});

test('custom feature entry updates validated payload and automatic title formula is configurable',async({page})=>{await composer(page);const features=page.locator('.property-features');await features.locator('summary').click();await features.getByRole('button',{name:'Add feature'}).click();await features.getByLabel('Feature name').fill('Balcony');expect(JSON.parse(await features.locator('[name="customFeatures"]').inputValue())).toEqual([{label:'Balcony',icon:'balcony'}]);const unit=page.locator('.composer-section').filter({hasText:'Unit & availability'});await page.locator('.listing-steps button').nth(1).click();await unit.locator('.advanced-unit-settings summary').click();await unit.getByRole('button',{name:'Location'}).click();await page.locator('[data-base-name="unitType"]').selectOption({label:'Studio'});await expect(page.locator('[data-base-name="roomName"]')).toHaveValue('Studio')});

test('listing preview includes selected property photos',async({page})=>{await composer(page);await page.locator('.property-media-input').setInputFiles({name:'preview.jpg',mimeType:'image/jpeg',buffer:Buffer.from('preview')});await page.getByRole('button',{name:'Preview listing'}).click();await expect(page.locator('.listing-draft-preview .preview-media img')).toHaveCount(1)});

test('header hides while scrolling and returns after scrolling stops',async({page})=>{await composer(page);await page.evaluate(()=>{document.body.style.minHeight='2200px';scrollTo(0,700)});await page.waitForTimeout(60);await expect(page.locator('.topbar')).toHaveClass(/scroll-hidden/);await page.waitForTimeout(260);await expect(page.locator('.topbar')).not.toHaveClass(/scroll-hidden/)});

test('back button remains transparent',async({page})=>{await open(page);await page.evaluate(row=>{vacancies=[row];history.replaceState(null,'','#detail/'+row.id);renderDetail(row.id)},vacancy);const back=page.locator('.page-back');await expect(back).toBeVisible();expect(await back.evaluate(node=>getComputedStyle(node).backgroundColor)).toBe('rgba(0, 0, 0, 0)')});

test('backend sends custom feature data through the protected property RPC',async({page})=>{await open(page);const result=await page.evaluate(async()=>{const original=window.fetch;let request;window.fetch=async(url,options)=>{request={url:String(url),body:JSON.parse(options.body)};return new Response(JSON.stringify([]),{status:200,headers:{'Content-Type':'application/json'}})};try{await VACANCY_BACKEND.setPropertyFeatures('00000000-0000-0000-0000-000000000061',[{label:'Balcony',icon:'balcony'}]);return request}finally{window.fetch=original}});expect(result.url).toContain('/rpc/set_property_custom_features');expect(result.body.p_features).toEqual([{label:'Balcony',icon:'balcony'}])});
