const {test,expect}=require('@playwright/test');
const APP=process.env.VACANCY_E2E_URL||'http://127.0.0.1:4173';

async function open(page){await page.route('**/rest/v1/vacancies?**',route=>route.fulfill({status:200,contentType:'application/json',body:'[]'}));await page.goto(`${APP}/#home`);await page.waitForFunction(()=>booting===false)}

test('header and footer use the supplied high-resolution responsive logo in both themes',async({page})=>{await open(page);for(const theme of ['light','dark']){await page.evaluate(value=>{document.documentElement.dataset.theme=value;renderHome()},theme);for(const selector of ['.brand','.footer-brand']){const logo=page.locator(`${selector} .brand-logo`);await expect(logo).toBeVisible();const result=await logo.evaluate(node=>{const box=node.getBoundingClientRect();return{loaded:node.complete&&node.naturalWidth>0,ratio:node.naturalWidth/node.naturalHeight,height:box.height,pixelDensity:node.naturalHeight/box.height,background:getComputedStyle(node).backgroundColor}});expect(result.loaded).toBe(true);expect(result.ratio).toBeGreaterThan(2.5);expect(result.height).toBeGreaterThanOrEqual(20);expect(result.pixelDensity).toBeGreaterThan(12);if(theme==='dark')expect(result.background).not.toBe('rgba(0, 0, 0, 0)')}}});

test('loading screen uses the supplied logo without the retired text mark',async({page})=>{await open(page);await page.evaluate(()=>renderLoading());await expect(page.locator('.loading-screen')).toBeVisible();const logo=page.locator('.loading-logo');await expect(logo).toBeVisible();expect(await logo.evaluate(node=>node.complete&&node.naturalWidth>0)).toBe(true);await expect(page.locator('.loading-mark,.loading-word')).toHaveCount(0)});

test('sign-in page uses the same high-resolution supplied logo',async({page})=>{await open(page);await page.evaluate(()=>{currentUser=null;renderAuth()});const logo=page.locator('.auth-brand .brand-logo');await expect(logo).toBeVisible();const proof=await logo.evaluate(node=>({loaded:node.complete&&node.naturalWidth>0,pixelDensity:node.naturalHeight/node.getBoundingClientRect().height}));expect(proof.loaded).toBe(true);expect(proof.pixelDensity).toBeGreaterThan(12);await expect(page.locator('.auth-brand')).toHaveAttribute('aria-label','Vacancy home')});

test('wordmark pixels are neutral black while transparency is preserved',async({page})=>{await open(page);const proof=await page.evaluate(async()=>{const image=new Image();image.src='assets/vacancy-logo.png';await image.decode();const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const context=canvas.getContext('2d');context.drawImage(image,0,0);const pixels=context.getImageData(0,0,canvas.width,canvas.height).data;let word=0,nonBlack=0;for(let y=0;y<canvas.height;y+=8){for(let x=550;x<canvas.width;x+=8){const index=(y*canvas.width+x)*4,r=pixels[index],g=pixels[index+1],b=pixels[index+2],a=pixels[index+3];if(a>20){word++;if(r!==0||g!==0||b!==0)nonBlack++}}}return{cornerAlpha:pixels[3],word,nonBlack}});expect(proof.cornerAlpha).toBe(0);expect(proof.word).toBeGreaterThan(1000);expect(proof.nonBlack).toBe(0)});
