const {test,expect}=require('@playwright/test');
const APP_URL=process.env.VACANCY_E2E_URL;
const vacancy={id:'guest-v',rentAmount:18000,rentCurrency:'KES',rentPeriod:'month',deposit:0,billsIncluded:false,availableFrom:'2026-10-01',minimumStayWeeks:null,room:{id:'r',name:'Guest-ready studio',roomType:'Studio',furnished:false,ensuite:false,maxOccupants:1,description:'A test vacancy',media:[]},property:{id:'p',title:'Guest house',suburb:'Kasarani',city:'Nairobi',state:'Nairobi',country:'Kenya',parkingSpaces:0,petsConsidered:false,smokingAllowed:false,householdSummary:'Quiet property',waterAvailable:true,electricityAvailable:true,securityAvailable:true,internetAvailable:false,publicLatitude:-1.2,publicLongitude:36.9},owner:{id:'owner',displayName:'Owner',bio:''}};

async function open(page){await page.route('**/rest/v1/vacancies?**',route=>route.fulfill({status:200,contentType:'application/json',body:'[]'}));await page.goto(`${APP_URL}/#home`);await page.waitForFunction(()=>booting===false);await page.evaluate(v=>{currentUser=null;vacancies=[v];renderDetail(v.id)},vacancy)}

test('visitor reaches the enquiry form without registration',async({page})=>{await open(page);await page.getByRole('button',{name:'Enquire'}).click();await expect(page).toHaveURL(/#enquire\/guest-v$/);await expect(page.getByLabel('Your name')).toBeVisible();await expect(page.getByText(/no account or password needed/i)).toBeVisible()});

test('visitor gets a guest session and sends a private enquiry',async({page})=>{await open(page);await page.getByRole('button',{name:'Enquire'}).click();await page.evaluate(()=>{window.__guestCalls=[];VACANCY_BACKEND.signInGuest=async name=>{window.__guestCalls.push(['guest',name]);currentUser={id:'guest',is_anonymous:true};return{}};VACANCY_BACKEND.currentUser=async()=>currentUser;VACANCY_BACKEND.savedIds=async()=>[];VACANCY_BACKEND.startEnquiry=async(id,input)=>window.__guestCalls.push(['enquiry',id,input.message]);VACANCY_BACKEND.conversations=async()=>[]});await page.getByLabel('Your name').fill('Amina');await page.getByLabel('Move-in date').fill('2026-10-10');await page.getByLabel('Message').fill('Can I view this studio on Saturday?');await page.getByRole('button',{name:'Send enquiry'}).click();await expect(page).toHaveURL(/#messages$/);expect(await page.evaluate(()=>window.__guestCalls)).toEqual([['guest','Amina'],['enquiry','guest-v','Can I view this studio on Saturday?']])});

test('guest session cannot enter account-only surfaces',async({page})=>{await open(page);await page.evaluate(()=>{currentUser={id:'guest',is_anonymous:true};renderList()});await expect(page).toHaveURL(/#auth$/);await expect(page.locator('#toast')).toContainText('Sign in to list a vacancy')});

test('guest signup request contains no email or password',async({page})=>{await open(page);let body;await page.route('**/auth/v1/signup',async route=>{body=route.request().postDataJSON();await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({access_token:'header.eyJleHAiOjQxMDI0NDQ4MDB9.sig',refresh_token:'refresh',user:{id:'guest',is_anonymous:true}})})});await page.evaluate(()=>VACANCY_BACKEND.signInGuest('Amina'));expect(body).toEqual({data:{display_name:'Amina'}});expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('vacancy-session-v01')).user.is_anonymous)).toBeTruthy()});
