const {test,expect}=require('@playwright/test');
const APP=process.env.VACANCY_E2E_URL||'http://127.0.0.1:4173';
async function open(page){await page.route('**/rest/v1/vacancies?**',route=>route.fulfill({status:200,contentType:'application/json',body:'[]'}));await page.goto(`${APP}/#home`);await page.waitForFunction(()=>booting===false&&typeof card==='function')}
const vacancy={id:'v1',rentAmount:24000,rentCurrency:'KES',rentPeriod:'month',deposit:12000,updatedAt:new Date(Date.now()-4*60*1000).toISOString(),room:{id:'r1',name:'Studio',roomType:'Studio',furnished:true,ensuite:true,media:[{url:'one.jpg'}]},property:{id:'p1',suburb:'Kilimani',city:'Nairobi',country:'Kenya',parkingSpaces:1,securityAvailable:true,internetAvailable:true,waterAvailable:true,electricityAvailable:true,publicLatitude:-1.21,publicLongitude:36.81},owner:{id:'o1'}};

test('cards use a familiar pin and reveal more facts in list view',async({page})=>{await open(page);await page.evaluate(row=>{vacancies=[row];searchCenter={lat:-1.2,lon:36.8};renderHome()},vacancy);await expect(page.locator('.listing-location use')).toHaveAttribute('href','#icon-location-pin');await expect(page.locator('.quick-searches')).toHaveCount(0);await expect(page.locator('.card-view .list-detail').first()).toBeHidden();await page.getByRole('button',{name:'List view'}).click();await expect(page.locator('.list-view .listing-distance')).toBeVisible();await expect(page.locator('.list-view .service-card-pill')).toHaveCount(7)});

test('listing starts with type and destination questions',async({page})=>{await open(page);await page.evaluate(async()=>{currentUser={id:'owner'};VACANCY_BACKEND.myProperties=async()=>[];VACANCY_BACKEND.myVacancies=async()=>[];await renderList()});await expect(page.getByRole('heading',{name:'What are you listing?'})).toBeVisible();await page.getByRole('button',{name:'Studio',exact:true}).click();await expect(page.getByRole('button',{name:'Studio',exact:true})).toHaveClass(/selected/);await page.getByRole('button',{name:'New property'}).click();const form=page.locator('#listingForm');await expect(form).toBeVisible();await expect(form.locator('.composer-section summary strong').first()).toHaveText('Property details');await expect(form.locator('[name="unitType"]')).toHaveValue('Studio')});

test('manual address offers a selectable free-geocoder suggestion and errors',async({page})=>{await open(page);await page.route('**/api/geocode?q=*',async route=>{const q=new URL(route.request().url()).searchParams.get('q');await route.fulfill({status:q.includes('bad')?404:200,contentType:'application/json',body:JSON.stringify(q.includes('bad')?{error:'Address not found'}:{lat:-1.2,lon:36.8,label:'12 Market Road, Nairobi'})})});await page.evaluate(async()=>{currentUser={id:'owner'};VACANCY_BACKEND.myProperties=async()=>[];VACANCY_BACKEND.myVacancies=async()=>[];await renderList()});await page.getByRole('button',{name:'House',exact:true}).click();await page.getByRole('button',{name:'New property'}).click();await page.locator('.composer-section').filter({hasText:'Location'}).locator('summary').click();await page.getByRole('button',{name:'Enter address manually'}).click();const address=page.locator('[name="address"]');await address.fill('12 Market');await expect(page.locator('.address-autocomplete button')).toHaveText('12 Market Road, Nairobi',{timeout:3000});await page.locator('.address-autocomplete button').click();await expect(address).toHaveValue('12 Market Road, Nairobi');await address.fill('bad address');await expect(page.locator('.address-autocomplete')).toContainText('Address not found',{timeout:3000})});

test('selected photos render a main image grid with expandable compact overflow',async({page})=>{await open(page);await page.evaluate(async()=>{currentUser={id:'owner'};VACANCY_BACKEND.myProperties=async()=>[];VACANCY_BACKEND.myVacancies=async()=>[];await renderList()});await page.getByRole('button',{name:'Apartment',exact:true}).click();await page.getByRole('button',{name:'New property'}).click();await page.getByRole('button',{name:'Add photos first'}).click();await page.locator('[name="images"]').setInputFiles(Array.from({length:5},(_,index)=>({name:`photo-${index+1}.jpg`,mimeType:'image/jpeg',buffer:Buffer.from([255,216,255,217])})));await expect(page.locator('.photo-selection-grid .photo-selection-item')).toHaveCount(4);await expect(page.locator('.photo-selection-grid .photo-main')).toHaveCount(1);await page.locator('[data-photo-expand]').click();await expect(page.locator('.photo-selection-grid .photo-selection-item')).toHaveCount(5)});

test('saving uses listing language',async({page})=>{await open(page);await page.evaluate(async row=>{currentUser={id:'member'};VACANCY_BACKEND.saveVacancy=async()=>[];vacancies=[row];searchCenter={lat:-1.2,lon:36.8};renderHome();await toggleSave(row.id)},vacancy);await expect(page.locator('#toast')).toContainText('Listing saved')});
