const {test, expect} = require('@playwright/test');
const APP = process.env.VACANCY_E2E_URL || 'http://127.0.0.1:4173';
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScL/nwAAAABJRU5ErkJggg==','base64');

test('three units keep private names separate and each gets its own preview', async ({page}) => {
  await page.setViewportSize({width:390,height:844});
  await page.route('**/rest/v1/vacancies?**', route => route.fulfill({status:200,contentType:'application/json',body:'[]'}));
  await page.goto(`${APP}/#home`);
  await page.waitForFunction(() => booting === false);
  await page.evaluate(async () => { currentUser={id:'owner'}; VACANCY_BACKEND.myProperties=async()=>[]; VACANCY_BACKEND.myVacancies=async()=>[]; await renderList(); });
  await page.locator('[data-listing-type=Residential]').click();
  await page.locator('[data-preset=Studio]').click();
  await page.getByRole('button',{name:'New property'}).click();
  const form=page.locator('#listingForm');
  await page.evaluate(() => { const form=document.querySelector('#listingForm'); for(const [key,value] of Object.entries({region:'Nairobi',city:'Nairobi',locality:'Westlands',address:'Example Road'}))form.elements[key].value=value; form.querySelector('#newPropertyMap')._vacancySetLocation(-1.26,36.8,false); });
  await form.locator('.journey-next').click();
  await expect(form).toHaveAttribute('data-journey-step','1');
  await expect(form.locator('.journey-current-title')).toHaveText('Listing details');
  await expect(form.locator('[name=propertyTitle]')).toBeVisible();
  await expect(form.locator('.property-media-pool')).toBeHidden();
  const first=form.locator('.unit-editor').first();
  await expect(first.locator('[data-base-name=roomName]')).toHaveValue('Studio in Westlands');
  const originalTitle=await first.locator('[data-base-name=roomName]').inputValue();
  await first.locator('.unit-name-input').fill('Flamingo A1');
  await expect(first.locator('[data-base-name=roomName]')).toHaveValue(originalTitle);
  await first.locator('.unit-features summary').click();
  await first.locator('[data-unit-amenity=Furnished]').click();
  await first.locator('[data-add-unit-option=amenity]').click();
  await first.locator('.unit-custom-amenities input').fill('Rooftop terrace');
  await first.locator('.unit-utilities summary').click();
  await first.locator('[data-add-unit-option=utility]').click();
  await first.locator('.unit-custom-utilities input').fill('Solar power');
  await first.locator('.unit-rules summary').click();
  await first.locator('[data-add-unit-option=rule]').click();
  await first.locator('.unit-rule-row input').fill('Smoking');
  await first.locator('.unit-rule-row [data-allowed=false]').click();
  await first.locator('[data-base-name=rentAmount]').fill('25000');
  await first.locator('input[type=file]').setInputFiles([1,2,3].map(number=>({name:`photo${number}.png`,mimeType:'image/png',buffer:png})));
  await expect(first.locator('.unit-media-toolbar button')).toHaveText('+ Add media');
  await expect.poll(()=>first.locator('img').count()).toBeGreaterThanOrEqual(3);
  await first.locator('.duplicate-unit-menu summary').click();
  await first.locator('.duplicate-same-property').click();
  await expect(form.locator('.unit-editor')).toHaveCount(2);
  const second=form.locator('.unit-editor').nth(1);
  await expect(second.locator('.unit-name-input')).toHaveValue('Flamingo A1 (copy)');
  await expect(second.locator('[data-base-name=roomName]')).toHaveValue(originalTitle);
  await second.locator('.duplicate-unit-menu summary').click();
  await second.locator('.duplicate-same-property').click();
  await expect(form.locator('.unit-editor')).toHaveCount(3);
  const third=form.locator('.unit-editor').nth(2);
  await expect(third.locator('.unit-name-input')).toHaveValue('Flamingo A1 (copy) (copy)');
  await third.locator('.unit-name-input').fill('Flamingo A3');
  await expect(third.locator('[data-base-name=roomName]')).toHaveValue(originalTitle);
  await form.locator('.journey-next').click();
  await expect(form).toHaveAttribute('data-journey-step','2');
  await expect(form.locator('.unit-draft-preview')).toHaveCount(3);
  await expect(form.locator('.unit-draft-preview').first()).toContainText('25,000');
  await expect(form.locator('.unit-draft-preview').first()).toContainText('Rooftop terrace');
  await expect(form.locator('.unit-draft-preview').first()).toContainText('No smoking');
  await expect(form.locator('.unit-draft-preview').first().locator('img')).toHaveCount(3);
  const imageStyle=await form.locator('.unit-draft-preview img').first().evaluate(img=>({ratio:getComputedStyle(img).aspectRatio,fit:getComputedStyle(img).objectFit}));
  expect(imageStyle).toEqual({ratio:'4 / 3',fit:'cover'});
  const details=await first.locator('[data-base-name=unitDetails]').inputValue();
  expect(JSON.parse(details)).toMatchObject({amenities:[{label:'Furnished'},{label:'Rooftop terrace'}],utilities:[{label:'Solar power'}],rules:[{label:'Smoking',allowed:false}]});
  await page.evaluate(() => {
    window.__created=[]; window.__saved=[];
    VACANCY_BACKEND.createListing=async input=>{window.__created.push(input);return 'vacancy-1'};
    VACANCY_BACKEND.createRoomVacancyForProperty=async (_property,input)=>{window.__created.push(input);return `vacancy-${window.__created.length}`};
    VACANCY_BACKEND.listingForEdit=async()=>({propertyId:'property-1'});
    VACANCY_BACKEND.saveUnitListingDetails=async(id,details,name)=>{window.__saved.push({id,details,name})};
    VACANCY_BACKEND.uploadListingImages=async()=>[];
    VACANCY_BACKEND.trackEvent=()=>{};
  });
  await form.locator('.listing-submit-actions button.primary').click();
  await expect.poll(()=>page.evaluate(()=>window.__saved.length)).toBe(3);
  const saved=await page.evaluate(()=>window.__saved);
  expect(saved.map(unit=>unit.name)).toEqual(['Flamingo A1','Flamingo A1 (copy)','Flamingo A3']);
  expect(saved[0].details.amenities).toEqual(saved[1].details.amenities);
});

test('public listing shows only its own selected options and rule wording', async ({page}) => {
  await page.route('**/rest/v1/vacancies?**', route => route.fulfill({status:200,contentType:'application/json',body:'[]'}));
  await page.goto(`${APP}/#home`);
  await page.waitForFunction(() => booting === false);
  await page.evaluate(() => {
    const id='11111111-1111-4111-8111-111111111111';
    vacancies=[{id,rentAmount:25000,rentCurrency:'KES',rentPeriod:'month',deposit:10000,billsIncluded:false,room:{id:'room-1',name:'Studio in Westlands',roomType:'Studio',unitDetails:{parkingSpaces:1,amenities:[{label:'Balcony',icon:'balcony'}],utilities:[{label:'Solar power',icon:'bolt'}],rules:[{label:'Smoking',allowed:false}]},media:[]},property:{id:'property-1',suburb:'Westlands',city:'Nairobi',country:'Kenya',parkingSpaces:0,publicLatitude:-1.26,publicLongitude:36.8},owner:{id:'owner-1',displayName:'Lister'}}];
    VACANCY_BACKEND.trackEvent=()=>{};
    nav('detail',id);
  });
  await expect(page.locator('.quiet-detail')).toBeVisible();
  await expect(page.locator('.quiet-features')).toContainText('Solar power');
  await expect(page.locator('.quiet-features')).toContainText('Balcony');
  await expect(page.locator('.quiet-rules')).toContainText('No smoking');
  await expect(page.locator('.quiet-terms')).not.toContainText('Check with lister');
});
