const {test,expect}=require('@playwright/test');
const APP_URL=process.env.VACANCY_E2E_URL||'http://127.0.0.1:4173';
async function openComposer(page){await page.route('**/rest/v1/vacancies?**',r=>r.fulfill({status:200,contentType:'application/json',body:'[]'}));await page.addInitScript(()=>localStorage.setItem('vacancy-market-v1','KE'));await page.goto(APP_URL);await page.waitForFunction(()=>booting===false);await page.evaluate(async()=>{currentUser={id:'stage53'};VACANCY_BACKEND.myProperties=async()=>[];VACANCY_BACKEND.myVacancies=async()=>[];await renderList()})}

test('listing begins at the top with a quiet map and current-location action',async({page})=>{await page.context().grantPermissions(['geolocation'],{origin:APP_URL});await page.context().setGeolocation({latitude:-1.286,longitude:36.817});await openComposer(page);const heading=await page.getByRole('heading',{name:'List a vacancy'}).boundingBox();expect(heading.y).toBeLessThan(140);await page.getByRole('button',{name:'Use current location'}).click();await expect(page.locator('[name=publicLatitude]')).toHaveValue('-1.286');await expect(page.locator('#newPropertyMap .leaflet-control-zoom')).toHaveCount(0);await expect(page.getByText('Approximate public map location')).toHaveCount(0);await expect(page.getByText(/Tap the map to place/)).toHaveCount(0);expect(await page.locator('#newPropertyMap').evaluate(n=>getComputedStyle(n).borderRadius)).toBe('0px')});

test('compact fields, single service states and section guidance reduce form load',async({page})=>{await openComposer(page);await expect(page.locator('.compact-field')).not.toHaveCount(0);await page.locator('.listing-steps button').nth(1).click();const service=page.locator('.composer-section[open] .service-choice').filter({hasText:'Water'});await expect(service.locator('.service-state')).toHaveText('Yes');await service.locator('.service-state').click();await expect(service.locator('.service-state')).toHaveText('No');expect(await service.locator('.service-state').evaluate(n=>getComputedStyle(n).color)).toMatch(/153|27/);await expect(page.locator('.composer-section[open] summary small')).toHaveText('Tap to close');await expect(page.locator('.composer-section:not([open]) summary small').first()).toHaveText('Tap to open')});

test('advanced property and unit fields start hidden and can be revealed',async({page})=>{await openComposer(page);await page.locator('.listing-steps button').nth(1).click();const property=page.locator('.composer-section[open]');await property.locator('.advanced-unit-settings summary').click();await expect(property.getByText('Property notes')).toBeVisible();await expect(property.locator('[name=household]')).toBeHidden();await property.getByRole('button',{name:/Property notes/}).click();await expect(property.locator('[name=household]')).toBeVisible();await page.locator('.listing-steps button').nth(2).click();const unit=page.locator('.composer-section[open]');await unit.locator('.advanced-unit-settings summary').click();for(const name of ['availableFrom','minimumStayWeeks','description'])await expect(unit.locator(`[name=${name}]`)).toBeHidden();await unit.getByRole('button',{name:/Available from/}).click();await expect(unit.locator('[name=availableFrom]')).toBeVisible()});

test('automatic title defaults on and manual mode exposes the title input',async({page})=>{await openComposer(page);await page.locator('.listing-steps button').nth(2).click();const toggle=page.getByRole('button',{name:'Automatic title'});await expect(toggle).toBeVisible();await expect(page.locator('[name=roomName]')).toBeHidden();await toggle.click();await expect(page.getByRole('button',{name:'Manual title'})).toBeVisible();await expect(page.locator('[name=roomName]')).toBeVisible()});

test('inventory has status filtering without an unused view switch',async({page})=>{await openComposer(page);await expect(page.locator('#vacancyFilter')).toBeVisible();await expect(page.locator('#vacancyViewToggle,#vacancyListView,#vacancyCardView')).toHaveCount(0)});

test('find search uses a transparent north-east arrow',async({page})=>{await openComposer(page);await page.evaluate(()=>renderHome());await expect(page.locator('#searchBtn use')).toHaveAttribute('href','#icon-arrow-ne');const style=await page.locator('#searchBtn').evaluate(n=>({background:getComputedStyle(n).backgroundColor,color:getComputedStyle(n).color}));expect(style.background).toBe('rgba(0, 0, 0, 0)');expect(style.color).toBe('rgb(17, 17, 17)')});
