const {test,expect}=require('@playwright/test');
const APP=process.env.VACANCY_E2E_URL||'http://127.0.0.1:4173';
async function open(page){await page.route('**/rest/v1/vacancies?**',route=>route.fulfill({status:200,contentType:'application/json',body:'[]'}));await page.goto(`${APP}/#home`);await page.waitForFunction(()=>booting===false)}
function luminance(hex){const rgb=hex.match(/[a-f\d]{2}/gi).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2]}
function contrast(a,b){const [hi,lo]=[luminance(a),luminance(b)].sort((x,y)=>y-x);return (hi+.05)/(lo+.05)}
test('local Source Sans 3 loads and preserves a usable fallback stack',async({page})=>{await open(page);await page.waitForFunction(()=>document.fonts.check('17px "Source Sans 3"'));const body=await page.locator('body').evaluate(el=>({family:getComputedStyle(el).fontFamily,size:getComputedStyle(el).fontSize,line:getComputedStyle(el).lineHeight}));expect(body.family).toContain('Source Sans 3');expect(body.family).toContain('system-ui');expect(body.size).toBe('17px');expect(parseFloat(body.line)).toBeGreaterThanOrEqual(25)});
test('semantic action pairs pass AA and switch correctly by theme',async({page})=>{await open(page);expect(contrast('#c2410c','#ffffff')).toBeGreaterThanOrEqual(4.5);expect(contrast('#fb923c','#18181b')).toBeGreaterThanOrEqual(4.5);for(const [theme,bg,fg] of [['light','rgb(194, 65, 12)','rgb(255, 255, 255)'],['dark','rgb(251, 146, 60)','rgb(24, 24, 27)']]){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);const button=page.locator('.list-action');await expect(button).toHaveCSS('background-color',bg);await expect(button).toHaveCSS('color',fg)}});
test('typography hierarchy and neutral deposit state render in both themes',async({page})=>{await open(page);await page.evaluate(()=>{app.innerHTML='<article class="listing-card"><h3>Studio in Kilimani</h3><span class="price">KSh 24,000</span><span class="deposit-card-pill">Deposit KSh 12,000</span></article>'});for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await expect(page.locator('.listing-card h3')).toHaveCSS('font-weight','600');await expect(page.locator('.price')).toHaveCSS('font-weight','700');const deposit=await page.locator('.deposit-card-pill').evaluate(el=>({color:getComputedStyle(el).color,bg:getComputedStyle(el).backgroundColor}));expect(deposit.color).not.toBe('rgb(185, 28, 28)');expect(deposit.bg).not.toBe('rgb(254, 242, 242)')}});
test('critical controls expose comfortable targets and the page does not overflow',async({page})=>{await open(page);for(const selector of ['.list-action','.theme-toggle','.mobile-nav button']){const boxes=await page.locator(selector).evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect()).filter(box=>box.width>0&&box.height>0));if(selector!=='.mobile-nav button'||await page.evaluate(()=>innerWidth<=820))expect(boxes.length).toBeGreaterThan(0);expect(boxes.every(box=>box.height>=48)).toBeTruthy()}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBeTruthy()});
