const {test,expect}=require('@playwright/test');
const APP=process.env.VACANCY_E2E_URL||'http://127.0.0.1:4173';
async function open(page,hash='home'){await page.route('**/rest/v1/vacancies?**',route=>route.fulfill({status:200,contentType:'application/json',body:'[]'}));await page.addInitScript(()=>localStorage.setItem('vacancy-market-v1','KE'));await page.goto(`${APP}/#${hash}`);await page.waitForFunction(()=>booting===false)}
async function composer(page){await open(page);await page.evaluate(async()=>{currentUser={id:'owner'};VACANCY_BACKEND.myProperties=async()=>[];VACANCY_BACKEND.myVacancies=async()=>[];await renderList()});await page.getByRole('button',{name:'Shop',exact:true}).click();await page.getByRole('button',{name:'New property'}).click()}

test('brand tap has no grey highlight or active background',async({page})=>{await open(page);const style=await page.locator('.brand').evaluate(node=>({tap:getComputedStyle(node).webkitTapHighlightColor,active:node.matches(':active')?getComputedStyle(node).backgroundColor:null,outline:getComputedStyle(node).outlineStyle}));expect(style.tap).toMatch(/rgba\(0, 0, 0, 0\)|transparent/);expect(style.outline).toBe('none')});
test('discovery removes recommendations and search-centre label',async({page})=>{await open(page);await expect(page.locator('.quick-searches,.user-location-status')).toBeHidden();await expect(page.locator('#q')).not.toHaveAttribute('list')});
test('map attribution is hidden only while tools cover it',async({page})=>{await open(page);await expect(page.locator('.leaflet-control-attribution')).toBeVisible();await page.getByRole('button',{name:'Map tools'}).click();await expect(page.locator('.map-first-shell')).toHaveClass(/filters-open/);await expect(page.locator('.leaflet-control-attribution')).toBeHidden()});
test('header controls are compact, centred and arrowless',async({page})=>{await open(page);const values=await page.evaluate(()=>{const currency=document.querySelector('#marketSelect'),theme=document.querySelector('#themeToggle'),list=document.querySelector('.list-action');return{currencyFont:getComputedStyle(currency).fontSize,currencyAppearance:getComputedStyle(currency).appearance,themeAlign:getComputedStyle(theme).placeItems,listAlign:getComputedStyle(list).justifyContent,listWeight:getComputedStyle(list).fontWeight}});expect(values.currencyFont).toBe('13px');expect(values.currencyAppearance).toBe('none');expect(values.themeAlign).toContain('center');expect(values.listAlign).toBe('center');expect(Number(values.listWeight)).toBeGreaterThanOrEqual(700)});
test('category filter changes visible map inventory',async({page})=>{await open(page);await page.evaluate(()=>{vacancies=[{id:'shop',rentAmount:1,rentCurrency:'KES',rentPeriod:'month',room:{name:'Shop',roomType:'Shop',media:[]},property:{propertyType:'Shop',marketCode:'KE',suburb:'A',city:'B',state:'',landmark:'',parkingSpaces:0},owner:{}},{id:'home',rentAmount:1,rentCurrency:'KES',rentPeriod:'month',room:{name:'House',roomType:'House',media:[]},property:{propertyType:'House',marketCode:'KE',suburb:'A',city:'B',state:'',landmark:'',parkingSpaces:0},owner:{}}];renderHome()});await page.getByRole('button',{name:'Map tools'}).click();await page.locator('[data-category="shop"]').click();await expect(page.locator('.listing-card')).toHaveCount(1);await expect(page.locator('.listing-card')).toContainText('Shop')});
test('listing choices include Shop and Other with custom category input',async({page})=>{await open(page);await page.evaluate(async()=>{currentUser={id:'owner'};VACANCY_BACKEND.myProperties=async()=>[];VACANCY_BACKEND.myVacancies=async()=>[];await renderList()});await expect(page.getByRole('button',{name:'Shop',exact:true})).toBeVisible();await page.getByRole('button',{name:'Other',exact:true}).click();await expect(page.getByLabel('Category name')).toBeVisible()});
test('custom listing category is carried into the saved form fields',async({page})=>{await open(page);await page.evaluate(async()=>{currentUser={id:'owner'};VACANCY_BACKEND.myProperties=async()=>[];VACANCY_BACKEND.myVacancies=async()=>[];await renderList()});await page.getByRole('button',{name:'Other',exact:true}).click();await page.getByLabel('Category name').fill('Warehouse');await page.getByRole('button',{name:'New property'}).click();await expect(page.locator('#listingForm [name="propertyType"]')).toHaveValue('Warehouse');await expect(page.locator('#listingForm [name="unitType"]').first()).toHaveValue('Warehouse')});
test('composer hides derived type and internal references while grouping optional fields',async({page})=>{await composer(page);await expect(page.locator('[name="propertyType"]')).toBeHidden();const advanced=page.locator('.composer-section').filter({hasText:'Property details'}).locator('.advanced-unit-settings').filter({hasText:'Advanced property'});await expect(advanced).toContainText('Property notes');await expect(advanced).toContainText('Minimum stay');await expect(page.locator('#listingHost')).not.toContainText('VAC-P-')});
test('auth is one unboxed form that switches to account creation',async({page})=>{await open(page);await page.evaluate(()=>{currentUser=null;renderAuth()});await expect(page.locator('#authUnified')).toHaveCount(1);await expect(page.locator('#signin,#signup')).toHaveCount(0);await expect(page.locator('.auth-brand')).toBeVisible();await page.getByRole('button',{name:'Create account'}).click();await expect(page.getByRole('heading',{name:'Create account'})).toBeVisible();await expect(page.getByLabel('Name')).toBeVisible()});
test('auth fields form one aligned vertical column',async({page})=>{await open(page);await page.evaluate(()=>{currentUser=null;renderAuth()});const boxes=await page.locator('#authUnified input:visible').evaluateAll(nodes=>nodes.map(node=>node.getBoundingClientRect()).map(({x,width,top})=>({x,width,top})));expect(boxes).toHaveLength(2);expect(Math.abs(boxes[0].x-boxes[1].x)).toBeLessThan(1);expect(Math.abs(boxes[0].width-boxes[1].width)).toBeLessThan(1);expect(boxes[1].top).toBeGreaterThan(boxes[0].top);const forgot=await page.locator('.forgot-link').boundingBox();expect(forgot.x+forgot.width).toBeLessThanOrEqual(boxes[0].x+boxes[0].width+1)});
test('listing publication requires at least three images',async({page})=>{await composer(page);const result=await page.evaluate(async()=>{const form=document.querySelector('#listingForm');form.querySelectorAll('[required]').forEach(input=>{if(input.type==='date')input.value='2026-10-01';else if(input.type==='number')input.value='1';else input.value='Test'});form.elements.publicLatitude.value='-1';form.elements.publicLongitude.value='36';form.requestSubmit();await new Promise(resolve=>setTimeout(resolve,20));return document.querySelector('#toast').textContent});expect(result).toContain('at least 3 images')});
