function renderAuth(){if(currentUser){nav('account');return}layout(`<section class="split"><form id="signin" class="panel form-grid"><h2 class="wide">Sign in</h2><label class="wide">Email<input name="email" type="email" required autocomplete="email"></label><label class="wide">Password<input name="password" type="password" required autocomplete="current-password"></label><button class="primary wide">Sign in</button></form><form id="signup" class="panel form-grid"><h2 class="wide">Create account</h2><label class="wide">Name<input name="name" required maxlength="80"></label><label class="wide">Email<input name="email" type="email" required autocomplete="email"></label><label class="wide">Password<input name="password" type="password" minlength="12" required autocomplete="new-password" pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{12,}" title="Use at least 12 characters with upper and lowercase letters and a number"></label><button class="primary wide">Create account</button><p class="muted wide">You may need to confirm your email before signing in.</p></form></section>`);document.querySelector('#signin').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));try{await VACANCY_BACKEND.signIn(f);await refreshIdentity();toast('Signed in');nav('home')}catch(err){toast(err.message)}};document.querySelector('#signup').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));try{const r=await VACANCY_BACKEND.signUp(f);if(r.access_token){await refreshIdentity();toast('Account created');nav('home')}else{toast('Check your email to confirm the account')}}catch(err){toast(err.message)}}}

async function renderAdmin(){
  if(!currentUser){nav('auth');return}
  layout('<section class="panel"><h1>Admin</h1><div id="adminHost" class="empty">Loading…</div></section>');
  const host=document.querySelector('#adminHost');
  try{const [data,rows,reports]=await Promise.all([VACANCY_BACKEND.adminOverview(),VACANCY_BACKEND.adminVacancies(),VACANCY_BACKEND.adminReports()]);if(data.error){host.textContent=data.error;return}host.className='stack';host.innerHTML=`<div class="stat-grid"><div class="stat"><strong>${data.users}</strong>Users</div><div class="stat"><strong>${data.active_vacancies}</strong>Active vacancies</div><div class="stat"><strong>${data.reports_open}</strong>Open reports</div><div class="stat"><strong>${data.messages}</strong>Messages</div></div><div class="panel"><h2>Listings</h2>${rows.map(r=>`<div class="row space"><span>${escapeHtml(r.rooms.name)} · ${escapeHtml(r.rooms.properties.suburb)} · ${r.status}</span>${r.status!=='removed'?`<button class="danger" data-admin-remove="${r.id}">Deactivate</button>`:''}</div>`).join('')||'<p class="muted">No listings.</p>'}</div><div class="panel"><h2>Reports</h2>${reports.map(r=>`<div><strong>${escapeHtml(r.reason)}</strong> <span class="muted">${r.status}</span></div>`).join('')||'<p class="muted">No reports.</p>'}</div>`;document.querySelectorAll('[data-admin-remove]').forEach(b=>b.onclick=async()=>{if(!confirm('Deactivate this vacancy?'))return;try{await VACANCY_BACKEND.adminDeactivateVacancy(b.dataset.adminRemove);toast('Vacancy deactivated');await renderAdmin()}catch(err){toast(err.message)}})}catch(err){host.textContent=err.message}
}
function renderAccount(){if(!currentUser){nav('auth');return}layout(`<section><div class="section-head"><div><h1>You</h1><p class="muted">${escapeHtml(currentUser.email||'Signed-in Vacancy member')}</p></div></div><div class="account-grid"><button class="account-action" id="yourListings"><div><strong>Your listings</strong><span>Properties, rooms, availability and edits</span></div><b>›</b></button><button class="account-action" id="listRoom"><div><strong>List a room</strong><span>Add a room to a new or existing property</span></div><b>＋</b></button><button class="account-action" id="adminEntry"><div><strong>Admin</strong><span>Moderation tools for authorised operators</span></div><b>›</b></button></div><div class="panel"><div class="row"><button class="ghost" id="signout">Sign out</button><button class="danger" id="deleteEntry">Delete account</button></div></div></section>`);document.querySelector('#yourListings').onclick=()=>nav('list');document.querySelector('#listRoom').onclick=()=>nav('list');document.querySelector('#signout').onclick=()=>{VACANCY_BACKEND.signOut();currentUser=null;saved.clear();toast('Signed out');nav('home')};document.querySelector('#adminEntry').onclick=()=>nav('admin');document.querySelector('#deleteEntry').onclick=async()=>{if(!confirm('Permanently delete your Vacancy account and associated data?'))return;try{await VACANCY_BACKEND.deleteAccount();currentUser=null;saved.clear();toast('Account deleted');nav('home')}catch(err){toast(err.message)}}}
function renderLoading(){layout('<div class="empty">Loading current vacancies…</div>')}
function renderError(){layout('<div class="empty"><strong>We could not load current vacancies.</strong><br><span class="muted">Please try again shortly.</span><br><button class="primary" id="retry">Retry</button></div>');document.querySelector('#retry').onclick=boot}
function render(){route=parseHash();if(route.name==='detail')renderDetail(route.id);else if(route.name==='saved')renderSaved();else if(route.name==='enquire')renderEnquire(route.id);else if(route.name==='messages')renderMessages();else if(route.name==='list')renderList();else if(route.name==='edit')renderEdit(route.id);else if(route.name==='auth')renderAuth();else if(route.name==='account')renderAccount();else if(route.name==='admin')renderAdmin();else renderHome()}
async function refreshIdentity(){currentUser=await VACANCY_BACKEND.currentUser();saved=new Set(currentUser?await VACANCY_BACKEND.savedIds():[])}
async function boot(){renderLoading();try{vacancies=await VACANCY_BACKEND.activeVacancies();await refreshIdentity();render()}catch(error){console.error(error);VACANCY_BACKEND.recordError('boot_load_failed',location.hash);renderError()}}
window.addEventListener('hashchange',render);boot();
